"""Laurence of Březová, Hussite chronicle, July 1419 to July 1420, from Fontes
rerum Bohemicarum V, ed. Jaroslav Goll (Prague 1893), pp. 344-396.

Page images: Czech Academy of Sciences, 'Czech medieval sources FONTES', book
1103, https://sources.cms.flu.cas.cz/src/online/1103/<n>.jpg with n = page+46.
Machine text for orientation: AHISTO portal (Masaryk University), book 1103.
Every excerpt was read against the page image. Goll prints the Latin in the
left column and the old Czech translation in the right; only the Latin is
carried. His text is kept as printed; his variant readings are not carried.
Cuts are marked [...].

The companion site The Hussite Field Armies carries Laurence from 22 August
1420 on; this module stops at the end of July 1420.

English: the site's working translation (CC0).

Each unit: pg (FRB V page), titel, orig, en, note."""

Y1419 = [
 {"pg": "344–345",
  "titel": "The mountain called Tábor",
  "orig": "Item anno domini MCCCCXIX sacerdotes evangelici Magistro Johanni Hus faventes et communionem calicis ad populum communem promoventes, tunc Wikleffiste et alias Hussite nuncupati, cum populo sexus utriusque ex diversis regni Bohemie partibus, civitatibus et villis cum sacramento eukaristie in montem quendam prope castrum Bechina, quem montem Thabor appellaverunt, frequentare ceperunt et ibidem populum communem sacra eukaristia precipue diebus festivis magna cum reverencia communicabant, emulis ipsius communionis populum communem in ecclesiis adiacentibus sic communicare non permittentibus. In festo autem sancte Marie Magdalene magna multitudine populi sexus utriusque et eciam parvulorum ad prefatum montem congregata de diversis regni prefati partibus, ultra quam XL millia personarum sacramento corporis et sanguinis domini sub utraque specie, panis scilicet et vini, secundum tradicionem Christi et praxim ac observanciam primitive ecclesie magna communicaverunt cum devocione. Quam ob rem rex Bohemie Wenceslaus multum est turbatus, se de regali solio deici timens et expavescens, Nicolaumque de Hus in locum sui substitui suspicando [...].",
  "en": "Item, in the year of the Lord 1419, the evangelical priests who favoured Master Jan Hus and promoted the communion of the chalice for the common people, then called Wycliffites or Hussites, began to resort, with people of both sexes from various parts, towns and villages of the kingdom of Bohemia, with the sacrament of the Eucharist, to a certain mountain near the castle of Bechyně, which they called Mount Tábor; and there they gave the common people communion in the holy Eucharist with great reverence, especially on feast days, since the opponents of that communion would not allow the common people to communicate so in the neighbouring churches. And on the feast of St Mary Magdalene a great multitude of people of both sexes, and of children too, gathered at the said mountain from various parts of the kingdom, more than forty thousand persons, and received the sacrament of the body and blood of the Lord in both kinds, bread and wine, according to the tradition of Christ and the practice and observance of the early Church, with great devotion. Because of this King Wenceslas of Bohemia was much disturbed, fearing and dreading that he would be cast down from the royal throne, and suspecting that Nicholas of Hus would be put in his place [...].",
  "note": "St Mary Magdalene's day is 22 July 1419. The name of the mountain is biblical: Tabor, the mount of the Transfiguration. Nicholas of Hus, a lord of southern Bohemia who had spoken for the chalice before the king, had been banished from Prague. The cut tells how. Laurence was a master of the Prague university and a moderate Utraquist, of the chalice but no friend of Tábor."},
 {"pg": "345–346",
  "titel": "The councillors thrown from the town hall",
  "orig": "Item anno eodem dominico die post Jacobi, alias XXX die mensis Julii, magister civium et consules aliqui Nove civitatis cum subiudice, communionis calicis emuli, per communem populum et Johannem Ziskam, regis Bohemie prefati familiarem, pro eo quod processioni illic iuxta pretorium cum sacramento venerabili eukaristie a sancto Stephano in Rybniczka ad monasterium beate Virginis in Arena redeunti insultaverunt, sunt de pretorio Nove civitatis enormiter deiecti et atrociter mactati et interfecti, rege Wenceslao pro tunc in Novo castro unum fere milliare a Praga distante cum sua curia consistente. Propter quod opus emulos veritatis in Praga magnus timor invasit [...]. Communitas vero ipsa quatuor capitaneos sibi usque ad futurorum eleccionem scabinorum elegit, quibus sigillum et alia consulatus insignia assignavit [...]. Unde rex Bohemie Wenceslaus ira magna motus et angustia ac dolore perturbatus proposuit omnes Wikleffistas seu Hussitas, et precipue sacerdotes extirpare. [...] Finaliter ergo parte utraque consenciente concluditur, quatenus communitas Nove civitatis se ipsi regi pro excessu, quem in deiciendo scabinos ab ipso deputatos et turpiter mactatos commiserat, humiliet et rex novos scabinos per ipsam tunc communitatem electos confirmet, quod et factum est cum effectu.",
  "en": "Item, in the same year, on the Sunday after St James, that is the 30th day of July, the burgomaster and some councillors of the New Town with the under-judge, opponents of the communion of the chalice, were outrageously thrown down from the town hall of the New Town by the common people and by Jan Žižka, a familiar of the said king of Bohemia, and were cruelly butchered and killed, because they had insulted a procession with the venerable sacrament of the Eucharist returning past the town hall from St Stephen's in Rybníček to the monastery of the Blessed Virgin in Na Písku; King Wenceslas was at that time at Nový Hrad, about a mile from Prague, with his court. Because of this deed a great fear fell on the opponents of the truth in Prague [...]. The community itself chose four captains until new aldermen should be elected, and handed over to them the seal and the other insignia of the council [...]. At this King Wenceslas of Bohemia, moved with great anger and troubled with anguish and grief, resolved to root out all the Wycliffites or Hussites, and above all the priests. [...] At last, with the consent of both sides, it was agreed that the community of the New Town should humble itself before the king for the excess it had committed in throwing down and shamefully killing the aldermen he had appointed, and that the king should confirm the new aldermen whom the community had then elected; and this was done in fact.",
  "note": "The first defenestration of Prague, 30 July 1419. Laurence names two agents, 'the common people' and Jan Žižka, here still 'a familiar of the king', a minor courtier; it is Žižka's first appearance in the chronicle. Modern accounts add that the procession was led by the preacher Jan Želivský; Laurence does not name him here. The town council had been appointed by the king; the deed was rebellion against him, and the settlement, the town humbled and its new aldermen confirmed, was the king's last act of authority in Prague. The cuts describe the summons to arms, the flight of the opponents and the negotiations."},
 {"pg": "346",
  "titel": "The death of King Wenceslas",
  "orig": "Item anno eodem feria IV post Assumpcionem beate virginis Marie, que erat dies XVI mensis Augusti, rex Bohemie Wenceslaus hora quasi vesperorum apoplexia percussus cum magno clamore et rugitu quasi leonis subito est extinctus in Novo castro prope Pragam, cuius corpus post dies aliquot propter timorem populi tempore nocturno ad castrum Pragense est deductum et in capella sancti Wenceslai, Boemorum patroni, collocatum et post septimanas aliquot abinde ad monasterium Aule Regie, ubi sepulturam sibi eligerat, noctis tempore miserrime transductum et a piscatoribus, pistoribus et conversis monasterii eiusdem sepultum. Cuius mors et acta ipsius cunctis regibus deberent fore in exemplum, quatenus deum timeant et eius legem ac veritatem pro posse tueantur et defendant.",
  "en": "Item, in the same year, on the Wednesday after the Assumption of the Blessed Virgin Mary, which was the 16th day of August, Wenceslas, king of Bohemia, struck by apoplexy at about the hour of vespers, died suddenly with a great cry and a roar like a lion's at Nový Hrad near Prague. After some days his body was carried by night, for fear of the people, to Prague Castle and laid in the chapel of St Wenceslas, patron of the Bohemians; and some weeks later it was taken from there by night, most wretchedly, to the monastery of Aula Regia, where he had chosen his burial, and buried by the fishermen, bakers and lay brothers of that monastery. His death and his deeds ought to be an example to all kings, that they may fear God and protect and defend his law and truth as far as they can.",
  "note": "Wenceslas IV died eighteen days after the defenestration. Aula Regia is the Cistercian abbey of Zbraslav south of Prague. The heir was his half-brother Sigismund, king of Hungary and of the Romans, who had given Hus his safe conduct. Laurence's moral is pointed: a king should defend God's law, and Wenceslas, as the chronicler saw it, had not."},
 {"pg": "347",
  "titel": "Images broken, the Charterhouse burned",
  "orig": "Item feria V post Assumpcionem beate Marie Virginis, alias die XVII mensis Augusti, sequenti scilicet die post mortem regis Wenceslai, quidam ex populo communi seu vulgo congregati magistri civium Antique civitatis Johannis scilicet Bradati cum consensu per ecclesias ac monasteria in civitate sita Pragensi omni timore postposito discurrebant et organa ac ymagines ecclesiarum precipue illarum, in quibus communio calicis minime admittebatur, plebanis ecclesiarum ac religiosis fugam ineuntibus seque a conspectu vulgi ipsius abscondentibus pre timore, confringebant, comminuebant ac violabant, adversariis veritatis timore magno ac tremore arescentibus. Tandemque de vespere Carthusiam pervenerunt et ipsam bonis quasi omnibus despoliantes, potagiis diversis ibidem inebriati et residuis ad terram effusis, religiosis omnibus monasterii eiusdem captivatis, ipsos processionaliter cum clamore valido et tumultu per pontem ad pretorium Antique deducunt civitatis pro eo, quod in mortem olim Magistri Johannis Hus consenserant et communioni utriusque speciei resistebant. Et in crastino, scilicet die Agapiti, que erat dies tercia post mortem regis Wenceslai, monasterium ipsum Carthusiense ignis consumunt voragine, muris ipsius dumtaxat resultantibus. [...] Item dominico die proximo post Assumpcionem beate Marie Virginis, alias die XX Augusti, monasterium predicatorum in Pieska funditus per communem populum utriusque sexus est dirutum et combustum, religiosis aliquibus monasterii ipsius captivatis.",
  "en": "Item, on the Thursday after the Assumption of the Blessed Virgin Mary, that is the 17th day of August, the day after King Wenceslas's death, some of the common people or crowd gathered, with the consent of the burgomaster of the Old Town, John Bradatý, and ran through the churches and monasteries of the city of Prague, all fear set aside, and broke, smashed and desecrated the organs and images of the churches, above all of those in which the communion of the chalice was not admitted, while the parish priests and the religious fled and hid from the crowd for fear, and the enemies of the truth withered with fear and trembling. At last, in the evening, they came to the Charterhouse and plundered it of almost all its goods; they got drunk there on various drinks and poured the rest on the ground, took all the monks of that monastery prisoner, and led them in procession with loud shouting and tumult over the bridge to the town hall of the Old Town, because they had consented to the death of Master Jan Hus and resisted the communion in both kinds. And on the next day, St Agapitus's day, the third day after King Wenceslas's death, they burned the Charterhouse itself, so that only its walls were left standing. [...] Item, on the Sunday after the Assumption, the 20th of August, the Dominican monastery 'in Pieska' was torn down to the ground and burned by the common people of both sexes, and some of its friars were taken prisoner.",
  "note": "The first days after the king's death, told by a chronicler of the chalice without excuse. The Charterhouse stood on the Smíchov side of the river. The cut tells of the tomb of Master Albík, the former archbishop, broken in the church of Our Lady 'in Lacu' (na Louži). The companion game names the violence of its own side as well as the enemy's; these are its first acts."},
 {"pg": "348–349",
  "titel": "Žižka joins the New Town",
  "orig": "Item feria III post Galli, alias die XVII mensis Octobris, regina Boemie Zophia et barones certi regni ipsius et presertim dominus Czenko de Wartemberg alias de Wesele, castri Pragensis purgravius supremus, Wilhelmus de Hazemburg dictus Zagiecz, Johanes Chudoba dictus Ralsko castrum Pragense, monasterium Strahow, monasterium sancti Thome curiamque archiepiscopi obsiderunt, Theutonicos et alios exteros in adiutorium sibi contra Pragenses super thesauris per mortem regis Wenceslai derelictis evocando. Sicque graves contenciones et guerre hiis diebus inter reginam et barones prefatos et inter Pragenses occasione libertande veritatis Christi et signanter calicis communionis, pro qua ipsa Pragensis communitas instabat, insurrexerunt. Item anno eodem feria IV ante festum Symonis et Jude apostolorum, alias die XXV mensis Octobris, communitas Nove civitatis obsedit castrum Wyssegradense, familia olim regis Wenceslai Bohemie inde depulsa. Cui communitati Johannes Ziska, familiaris prefati regis, se adiunxit. Item anno eodem sabbato post festum Omnium sanctorum, alias die IV mensis Novembris, hora quasi XXI ad incitacionem presbiterorum quorundam et presertim Ambrosii de Hradecz Regine campane magne in Praga pro concursu populi pulsantur ad subveniendum illis, qui de Thabor versus Pragam tendendo in itinere per barones regni et officiales regios insidiis positis impediebantur. [...] Fuit ergo nox illa multis nox tribulacionis et angustie, nox mesticie et luctus, novissime quasi diei assimilata, sic quod regina Zophia cum domino Ulrico de Rosis pre timore in medio noctis de castro Pragensi fugierunt, regalibus vix ipsum castrum ab acquirendo per Pragenses conservantibus.",
  "en": "Item, on the Tuesday after St Gall, that is the 17th day of October, Queen Sophia of Bohemia and certain barons of the kingdom, above all the lord Čeněk of Wartenberg, also called of Veselí, supreme burgrave of Prague Castle, William of Hasenburg called Zajíc, and John Chudoba called Ralsko, occupied Prague Castle, the monastery of Strahov, the monastery of St Thomas and the archbishop's court, and called in Germans and other foreigners to help them against the Praguers over the treasure the death of King Wenceslas had left. And so in these days grave quarrels and wars arose between the queen and the said barons and the Praguers, over the freeing of the truth of Christ and especially of the communion of the chalice, for which the community of Prague pressed. Item, in the same year, on the Wednesday before the feast of Simon and Jude, that is the 25th day of October, the community of the New Town besieged Vyšehrad castle, and drove out the household of the late King Wenceslas. Jan Žižka, a familiar of the said king, joined that community. Item, in the same year, on the Saturday after All Saints, that is the 4th day of November, at about the twenty-first hour, at the urging of certain priests and above all of Ambrose of Hradec Králové, the great bells in Prague were rung to call the people together to help those who were on their way from Tábor to Prague and were being stopped on the road by ambushes of the barons of the kingdom and the royal officers. [...] So that night was for many a night of tribulation and anguish, a night of sorrow and mourning, like the last day, so that Queen Sophia fled from Prague Castle for fear in the middle of the night with the lord Oldřich of Rožmberk, and the royal party barely kept the castle from being taken by the Praguers.",
  "note": "The queen dowager and the great officers held the castle for the heir, Sigismund; the towns of Prague held the chalice. Žižka, a minor courtier of the dead king, takes the town's side at Vyšehrad: the first act of the soldier the game makes you play. 'Tábor' here still means the gatherings on the hills of the south, not yet the town. The cut tells the fighting in the Lesser Town on 4 and 5 November, with dead on both sides, the archbishop's court sacked and the Lesser Town's town hall burned by the royal party."},
 {"pg": "350–351",
  "titel": "The truce of St Brice",
  "orig": "Item in die Briccii treuge pacis inter reginam Zophiam, dominum Czenkonem de Wartemberg, supremum regni Bohemie purgravium, et alios barones ac capitaneos castri Pragensis parte ex una et communitatem Pragensem parte ex altera usque ad festum Georgii de proximo venturum durature firmantur, senioribus partis utriusque ad hoc desudantibus, et pena L millium sexagenarum vallantur, regina cum baronibus se communitati Pragensi ad defendendum et pro posse per regnum Bohemie legem dei ac veritatem evangelicam et signanter speciei utriusque communionem libertandum proscribente, communitate vero Pragensi regine et baronibus se ad non ymagines confringendum et ad non ecclesias ac monasteria rumpendum asstringente, de Wyssegrado quoque regalibus condescendendum. Nova igitur civitas de Wyssegrado post ipsarum pacis treugarum firmacionem regalibus condescendit, de quo castro de post, ut inferius patere poterit, Pragensibus multa mala et dampna sunt illata. Item his pacis treugis, sicut prefertur, firmatis Thaborienses prefati magnis dampnis in domibus, in quibus commorabantur, per edificiorum destruccionem et spoliis in Minori parte perpetratis ad propria de Praga exeundo redierunt.",
  "en": "Item, on St Brice's day, a truce was concluded between Queen Sophia, the lord Čeněk of Wartenberg, supreme burgrave of the kingdom of Bohemia, and the other barons and captains of Prague Castle on the one side, and the community of Prague on the other, to last until the next feast of St George, the elders of both sides labouring for it, and guarded by a penalty of fifty thousand threescore of groats. The queen with the barons bound herself to the community of Prague to defend, as far as she could, the law of God and the truth of the gospel throughout the kingdom of Bohemia, and especially to set free the communion in both kinds; the community of Prague bound itself to the queen and the barons not to break images and not to break into churches and monasteries, and to hand Vyšehrad back to the royal party. So after the truce was concluded the New Town gave Vyšehrad back to the royal party, from which castle afterwards, as will appear below, much harm and damage was done to the Praguers. Item, when this truce had been concluded, the said Taborites left Prague and went home, having done great damage to the houses in which they had stayed by destroying the buildings, and having plundered in the Lesser Town.",
  "note": "13 November 1419, until 23 April 1420. The terms are the compromise of the moderate party: the chalice protected by the crown's officers, the images by the city. Vyšehrad, which Žižka had helped to take, went back to the king's men; Žižka himself left Prague soon after for Plzeň, where the radicals would make no truce at all (Laur. 1420 [1])."},
]

Y1420 = [
 {"pg": "355–356",
  "titel": "Five cities of refuge, and Žižka at Plzeň",
  "orig": "Item hiisdem temporibus sacerdotes quidam Thaborienses novum Christi adventum predicabant populo, in quo adventu omnes mali et veritatis emuli perire debeant et exterminari et boni dumtaxat in quinque conservari civitatibus. Qua de causa civitates quedam, in quibus libertatem calicis habebat communio, nullam cum adversariis inire volebant concordiam et precipue civitas Plznensis. [...] quatenus omnes et singuli ab ira dei omnipotentis, que secundum eorum opinionem in procinctu universo orbi erat ventura, salvari cupientes de civitatibus, castris, villis ac opidis sicut Loth de Sodomis ad quinque civitates refugii se transferant. Harum hec sunt nomina: Plzna, que per ipsos civitas solis est appellata, Zacz, Luna, Slana et Glatovia [...]. Hiis, sicut premittitur, currentibus ad civitatem Plznensem multi communionem zelantes calicis et presertim dominus Brzenko de Sswihow, dominus Walkun de Adlar, Johannes quoque Ziska, familiaris regis Bohemie olim Wenceslai, cum certa sua comitiva de Praga convenerunt et se in ipsa civitate emulis veritatis expulsis contra reginam Zophiam, baronesque ac ceteros regales precluserunt, treugas pacis cum eisdem nullomodo tamquam cum dei et sue legis inimicis inire volendo. Ad induccionem ergo sacerdotum et precipue Wenceslai dicti Coranda, qui pro tunc inter ipsos capitalis erat, monasteria civitatis ipsius et ecclesie curieque certe civitati adiacentes destruuntur et diruuntur.",
  "en": "Item, in these same times certain Taborite priests preached to the people a new coming of Christ, in which all the wicked and the enemies of the truth were to perish and be destroyed, and the good alone be preserved in five cities. For this reason certain towns in which the communion had the freedom of the chalice would make no agreement with their adversaries, above all the town of Plzeň. [...] that all who wished to be saved from the wrath of Almighty God, which, as they held, was about to come upon the whole world, should go out of the cities, castles, villages and towns, as Lot went out of Sodom, to the five cities of refuge. These are their names: Plzeň, which they called the city of the sun, Žatec, Louny, Slaný and Klatovy [...]. While these things were going on, many who were zealous for the communion of the chalice came together from Prague to the town of Plzeň, above all the lord Břeněk of Švihov, the lord Valkoun of Adlar, and Jan Žižka, a familiar of the late King Wenceslas of Bohemia, with a following of his own; they drove out the enemies of the truth and shut themselves up in that town against Queen Sophia, the barons and the other royalists, refusing to make any truce with them, as with enemies of God and of his law. At the urging of the priests, and above all of Wenceslas called Koranda, who was then the chief among them, the monasteries of the town and certain churches and courts near it were destroyed and torn down.",
  "note": "Winter 1419–1420. Laurence, a Prague master, has no sympathy for the millenarian preaching: the cut calls it a false reading of the prophets that drove simple people to sell their goods and lay the money at the priests' feet. Plzeň would not stay in radical hands; it became the stronghold of the Catholic party in western Bohemia. Koranda is the priest who, in July, had the benches of St Michael's carried off for the fort on Vítkov."},
 {"pg": "355",
  "titel": "The shafts of Kutná Hora",
  "orig": "Item feria III post Epiphaniam domini, alias die IX mensis Januarii, in galli cantu Magister Johannes Chodko, plebanus de Gurzim, cum ceteris presbiteris Jacobo, Martino, Leonardo per Montanos sunt ad foveam profundam seu ssachtam dictam Thabor miserabiliter proiecti, Magistro Johanne prefato Montanos, quatenus de tantis crudelitatibus, quas in Christi fideles communionem calicis zelantes immaniter exercebant, et de aliis penitenciam agant condignam, ammonente [...]. Eadem eciam nocte multi secularium propter calicis communionem per ipsos Montanos sunt interempti et ad ssachtas proiecti.",
  "en": "Item, on the Tuesday after Epiphany, that is the 9th day of January, at cockcrow, Master John Chodek, parish priest of Kouřim, with the other priests James, Martin and Leonard, was miserably thrown by the men of the Mountains into a deep pit or shaft called Tábor, after Master John had warned them to do fitting penance for the great cruelties they were savagely inflicting on the faithful of Christ who were zealous for the communion of the chalice [...]. On the same night many laymen too were killed by the men of the Mountains because of the communion of the chalice and thrown into the shafts.",
  "note": "Kutná Hora, the silver town whose German miners and burghers held for the old Church and for Sigismund ('Montani', the men of the Mountains). The killings in the mine shafts are the enemy's violence as Laurence records it; the game carries both sides. The cut is Laurence's remark that the miners received their punishment two years later."},
 {"pg": "359",
  "titel": "The crusade proclaimed, and a truce made in bad faith",
  "orig": "Item dominica Letare, die scilicet XVII Marcii, de mandato legati pape in Wratislavia pro tunc cum Sigismundo, Romanorum ac Hungarie rege, existente cruciata papalis contra Bohemos precipue calicis zelantes communionem, velud contra hereticos et ecclesie Romane rebelles, per ecclesias in sermonibus est proclamata. Infra idem tempus regales modis variis ac astuciis cum Thaboritis hiis, qui se in Plzna precluserant, personas per diversas de concordia tractant, qui nullam concordiam cum ipsis, tamquam cum infidelibus ac hereticis, veritatisque adversariis, inire volebant. Consilio tamen quorundam Pragensium ex parte ad ipsos missorum acquiescentes cum ipsis regalibus concordiam tandem sub hiis inierunt circumstanciis, primum quod in ipsa civitate communio calicis libertatem habeat; item quod ipsi libertatem plenam cum pueris et uxoribus suis se in Hradisst transferendi habeant. Ad quod regales prefati se certis asstrinxere sub penis, licet dolose. Magistro namque monete de Montibus dicto Mikess Diwoky, domino Petro de Ssternberg, magistroque ordinis sancti Johannis Jerosolimitani de Strakonicz ac ceteris regalibus cum magna equestrium multitudine in districtu Piescensi congregatis intimant occulte, quatenus dum Plznenses et Thaborite de Plzna exiverint, ipsos in itinere manu armata hostiliter invadant et prosternant, quod et factum est.",
  "en": "Item, on Laetare Sunday, that is the 17th of March, by order of the pope's legate, who was then at Breslau with Sigismund, king of the Romans and of Hungary, the papal crusade against the Bohemians, above all those zealous for the communion of the chalice, as against heretics and rebels against the Roman Church, was proclaimed in sermons in the churches. In the same time the royalists treated in various ways and with cunning, through various persons, for an agreement with the Taborites who had shut themselves up in Plzeň, who would make no agreement with them, as with unbelievers, heretics and enemies of the truth. Yet on the advice of certain men sent to them on behalf of the Praguers they agreed, and at last made an agreement with the royalists on these terms: first, that the communion of the chalice should have freedom in that town; next, that they should have full freedom to move with their children and wives to Hradiště. The royalists bound themselves to this under certain penalties, but in bad faith. For they secretly told the master of the mint of Kutná Hora, called Mikeš Divoký, the lord Peter of Šternberk, the master of the order of St John of Jerusalem at Strakonice and the other royalists, gathered with a great host of horsemen in the district of Písek, that when the men of Plzeň and the Taborites came out of Plzeň they should attack them on the road with armed force and destroy them; and so it was done.",
  "note": "At Breslau on 15 March the legate and Sigismund had burned a Prague merchant, John Krása, for refusing to say that the Council of Constance had condemned Hus justly; two days later the crusade was proclaimed. Hradiště is the hill above the Lužnice where the radicals were founding their own town, the new Tábor. Mikeš Divoký is the royal official who, Hus wrote from Constance, had told him he would be condemned (Letters [3])."},
 {"pg": "359–360",
  "titel": "Sudoměř: the wagons",
  "orig": "In die etenim Annunciacionis sancte Marie, que erat dies XXV mensis Marcii domino Brzenkone de Sswihow, Walkun de Adlar et Johanne Ziska cum aliis fratribus communioni calicis faventibus, sacerdotibus ipsorum et precipue Wenceslao Coranda et Marcoldo, qui se in civitate Plznensi contra regales precluserant, ut superius tactum est, de Plzna versus Hradisst tendentibus de civitate Plznensi sub condicionibus pretactis domino Wenceslao de Lesstna, regni subcamerario, condescendentibus, ipsos regales prefati prope Sudomierz iuxta piscinam quandam manu potenti hostiliter invadunt. Conflictu ergo inito et Thaboritis se curribus circumdantibus multi parte ab utraque corruerunt, multi quoque vulnerati sunt, inter quos dominus Brzenko in acie belli constitutus occiditur. Certamine tandem belli durante horis aliquot circa solis occasum regales de campis recedunt, fratribus XXX aliquot captivatis, quos magister monete ad Montes vinctos deducit. Fratres vero in Hradisst, vulneratis quibusdam in villis derelictis, perveniunt, fratribus ipsius montis ipsos grate excipientibus.",
  "en": "For on the day of the Annunciation of St Mary, which was the 25th day of March, when the lord Břeněk of Švihov, Valkoun of Adlar and Jan Žižka, with other brethren who favoured the communion of the chalice and their priests, above all Wenceslas Koranda and Markold, who had shut themselves up in the town of Plzeň against the royalists, as said above, were on their way from Plzeň to Hradiště, having given up the town of Plzeň to the lord Wenceslas of Leštno, under-chamberlain of the kingdom, on the said conditions, the said royalists attacked them in force near Sudoměř, by a certain fishpond. When battle was joined, and the Taborites had surrounded themselves with their wagons, many fell on both sides and many were wounded, among them the lord Břeněk, who was killed in the battle line. The fighting lasted some hours, until about sunset the royalists withdrew from the field, having taken some thirty of the brethren prisoner, whom the master of the mint led in chains to Kutná Hora. The brethren reached Hradiště, leaving some of the wounded in the villages, and the brethren of that mountain received them gladly.",
  "note": "The battle of Sudoměř, 25 March 1420, Žižka's first victory, and the first time the chronicle names the wagons: 'the Taborites surrounded themselves with their wagons'. Laurence does not say that Žižka commanded; the companion site The Hussite Field Armies follows the wagon fort from here. Wenceslas of Leštno is very probably Wenceslas of Dubá and Leštno, who had ridden to Constance with Hus (Mlad. Arrest [2])."},
 {"pg": "361–362",
  "titel": "Prague swears to defend the chalice",
  "orig": "Item feria IV ante Pascha, alias die III Aprilis Pragenses communionem utriusque speciei zelantes comperto, quod rex Hungarie Sigismundus nichil boni de eis et aliis veritatis fautoribus cogitat, ad instigacionem quorundam spiritualium, et presertim Johannis, predicatoris monasterii Nove civitatis Pragensis in Arena, ad pretorium Antique civitatis cum sacerdotibus et magistris calicis promoventibus communionem congregati se asstringunt communionem calicis contra quemlibet ipsam impugnare volentem defendere et tueri rebus et corporibus usque ad ultimum posse, proscripcionibus certis desuper factis iuramentum quoque fidelitatis ad standum fideliter pro veritatis defensa a scabinis, qui adhuc supererant, recipiunt, quatuor quoque capitaneos in Antiqua et quatuor in Nova constituunt civitatibus, quibus claves pretorii et valvarum mox assignant et auctoritatem omnimodam omnia et singula ad promocionem et defensam veritatum spectancia providendi, ordinandi et agendi committunt plenarie obedienciam ipsis promittendo.",
  "en": "Item, on the Wednesday before Easter, that is the 3rd day of April, the Praguers who were zealous for the communion in both kinds, having found out that Sigismund, king of Hungary, intended nothing good for them and the other friends of the truth, gathered at the town hall of the Old Town, at the urging of certain clergy and above all of John, the preacher of the monastery in Na Písku in the New Town of Prague, with the priests and masters who promoted the communion of the chalice, and bound themselves to defend and protect the communion of the chalice against anyone who would attack it, with their goods and their bodies to the uttermost; and having made certain proscriptions about it, they received an oath of fidelity from the aldermen who were still left, to stand faithfully for the defence of the truth, and appointed four captains in the Old Town and four in the New, to whom they at once handed the keys of the town hall and the gates, and committed to them full authority to provide, order and do everything that concerned the promotion and defence of the truths, promising them obedience.",
  "note": "Holy Week 1420: Prague becomes a sworn community under elected captains, as the New Town had done after the defenestration (Laur. 1419 [2]). John the preacher is Jan Želivský, the former Premonstratensian of Želiv, preacher at Our Lady of the Snows in the quarter called Na Písku, who preached the Apocalypse and called Sigismund the red dragon. The cut adds forty under-captains for each town."},
 {"pg": "362–363",
  "titel": "Tábor's captains, and the castle of Sedlec",
  "orig": "Item hiisdem diebus Thaborite de Hradisst electis ac erectis sibi quator capitaneis, ad quos respectum haberent, puta Nicolao de Hus, Johanne Ziska monoculo, olim familiari regis et legis Christi zelatore precipuo, de quo inferius multa tangentur, Sbynkone quoque de Buchow ac Chwalone de Rzepicz, municionem firmam Sedlecz nuncupatam prope Ustie manu hostili aggrediuntur, quam per impetum acquirunt, licet hii, qui intus erant, strenue restitissent, moxque dominum Ulricum, dominum civitatis Ustie, militem [...]. In hac ergo municione seu propugnaculo multa bona de vicinatu in auro, argento, monstranciis, calicibus ac vestibus preciosisque pro conservacione erant reposita, que omnia Thaborite efferentes et ad unum ponentes cumulum ignis voragine consumunt, municionem insuper ipsam diruunt et exurunt.",
  "en": "Item, in these same days the Taborites of Hradiště, having chosen and set up four captains for themselves, to whom they should look, namely Nicholas of Hus, Jan Žižka the one-eyed, once a familiar of the king and a foremost zealot for the law of Christ, of whom much will be said below, Zbyněk of Buchov and Chval of Řepice, attacked the strong castle called Sedlec near Ústí and took it by storm, although those inside resisted bravely; and at once the lord Oldřich, lord of the town of Ústí, a knight, [...]. In this castle or fortress many goods of the neighbourhood had been stored for safekeeping, in gold, silver, monstrances, chalices and precious vestments; the Taborites carried all of it out, put it in one heap and burned it, and then tore down and burned the castle itself.",
  "note": "April 1420. The first time Laurence calls Žižka 'one-eyed', and the first time he names him a captain of Tábor. The cut tells what the Taborites did to the lord of Ústí and the garrison: the lord was killed with flails and thrown into the fire, the defenders put to death except one, Pynta, who saved himself by beheading five of his comrades and joined the Taborites. The game names this as it names the enemy's killings at Kutná Hora (Laur. 1420 [2]). The burning of the treasure rather than its plunder is the Taborite rule against keeping the Church's wealth."},
 {"pg": "363",
  "titel": "The burgrave changes sides",
  "orig": "Item feria IV post Tiburcii, alias die XVII mensis Aprilis, dominus Czenko de Wartenberg, castri Pragensis supremus purgravius, a rege Hungarie Sigismundo sepefato de Wratislavia redeundo et cognito, quod ipse rex communionem calicis annulare vellet totaliter, expulsis adversariis omnibus communionis calicis tam spiritualibus quam secularibus, nobilibus et ignobilibus, mulieribus, puellis et parvulis de civitate Pragensi ad castrum Pragense cum bonis suis quasi infinitis confugientibus, castrum ipsum cum suis obsedit se cum Pragensi civitate uniens pro veritatis defensione, veritatis emulis precipue Theutonicis ad Montes et vicinas fugientibus civitates bonis infinitis in castro Pragensi derelictis.",
  "en": "Item, on the Wednesday after St Tiburtius, that is the 17th day of April, the lord Čeněk of Wartenberg, supreme burgrave of Prague Castle, returning from the said Sigismund, king of Hungary, at Breslau, and having learned that the king meant to do away with the communion of the chalice altogether, drove out all the opponents of the communion of the chalice, spiritual and secular, noble and common, women, girls and children, who had fled from the city of Prague to Prague Castle with almost endless goods, occupied the castle with his men and joined the city of Prague in defence of the truth; and the enemies of the truth, above all the Germans, fled to Kutná Hora and the neighbouring towns, leaving endless goods in Prague Castle.",
  "note": "The highest officer of the kingdom, who had signed the lords' protest of 1415 first among them (Protest [1]) and had held the castle against Prague in November 1419, changes sides when he learns what Sigismund intends. He did not hold to it: in May he handed the castle back to the king, and the crusaders held it when they came in June. The game's question in one card: which way do the lords go?"},
]

VITKOV = [
 {"pg": "384",
  "titel": "'Ha! ha! Hus! Hus! Heretic!'",
  "orig": "In hoc ergo exercitu, cuius multitudo ultra quam ad centum quinquaginta millia armatorum se extendebant, erant enim archiepiscopi, episcopi, patriarcha Aquilegiensis, doctores diversi ceterique prelati spirituales, duces et principes seculares, numero fere XL, marchiones, comites, barones et nobiles multi, milites, clientes, cives diversarum civitatum et rustici totam planiciem camporum premissorum occupando et tentoria seu tabernacula sumptuosa in similitudinem trium magnarum civitatum ordinando. Ibi diversarum nacionum fuere populi, tribus et lingue, Boemi et Moravi, Hungari et Croaci, Dalmaci et Bulgari, Walachi et Siculi, Cuni, Jasi, Ruteni, Rasi, Slavi, Pruteni, Servi, Turingi, Stirii, Misnenses, Bavari, Saxones, Australes, Franci, Francones, Anglici, Brabanti, Bestfali, Holandri, Sweyceri, Lusacenses, Swevi, Carintii, Aragones, Hispani, Poloni, Theutonici de Reno et alii quam plurimi. Hii ergo cottidie in vertice montis supra flumen ex opposito monasterii sancte Crucis et ecclesie sancti Valentini stantes contra civitatem ha! ha! hus! hus! kacer! kacer! velut canes ululabant [...].",
  "en": "In this army, whose numbers ran to more than a hundred and fifty thousand armed men, there were archbishops, bishops, the patriarch of Aquileia, various doctors and other spiritual prelates, secular dukes and princes to the number of about forty, margraves, counts, barons and many nobles, knights, squires, citizens of various towns and peasants, occupying the whole plain of the said fields and setting out costly tents and pavilions like three great cities. There were peoples, tribes and tongues of various nations: Bohemians and Moravians, Hungarians and Croats, Dalmatians and Bulgarians, Wallachians and Szeklers, Cumans, Jassians, Ruthenians, Rascians, Slavs, Prussians, Serbs, Thuringians, Styrians, Meisseners, Bavarians, Saxons, Austrians, French, Franconians, English, Brabanters, Westphalians, Hollanders, Swiss, Lusatians, Swabians, Carinthians, Aragonese, Spaniards, Poles, Germans from the Rhine and very many others. These stood every day on the top of the hill above the river opposite the monastery of the Holy Cross and the church of St Valentine, and howled at the city like dogs: 'Ha! ha! Hus! Hus! Kacer! Kacer!' [...]",
  "note": "The crusade proclaimed by Pope Martin V on 1 March 1420 against the heretics of Bohemia, under the command of Sigismund, before Prague in June and July 1420. Laurence's numbers are the chronicler's; modern estimates are much lower. 'Kacer' is the German Ketzer, heretic. The list of nations is the point: all Christendom against one city. The cut says that Bohemians who fell into the crusaders' hands were burned as heretics even if they had never taken the chalice."},
 {"pg": "385",
  "titel": "Žižka fortifies the hill",
  "orig": "Item cum rex Hungarie Sigismundus sic potenter, ut prefertur, campos cum intraneis et extraneis contra Pragensem teneret civitatem et intenderet montem prope patibulum dictum Witkowa hora suis munire gentibus, ut velut tercio castro Pragam sic stringeret, quod nullus civitati Pragensi liber pateret victualium accessus, hoc presciens Johannes Ziska, Thaboriensium capitaneus, absque dilacione mox in supradicto monte duo in modum stubarum disposuit fieri propugnacula, que parvulo fossato circumfodi mandavit et muro ex humo et lapidibus circumdari, per quod quidem propugnaculum dominus omnipotens miraculose salutem Pragensi contulit civitati, ita quod in eodem loco hostes prostrati amplius civitatem sic hostiliter invadere non attemptaverunt, ut patebit inferius.",
  "en": "Item, when Sigismund, king of Hungary, held the fields so powerfully against the city of Prague, as said above, with natives and foreigners, and intended to occupy with his men the hill near the gallows called Vítkova hora, so as to squeeze Prague as with a third castle, so that no free access for victuals should be open to the city of Prague, Jan Žižka, captain of the Taborites, knowing this beforehand, at once had two strongpoints built on that hill in the manner of log houses, which he ordered to be ringed with a small ditch and surrounded with a wall of earth and stones; and by this strongpoint Almighty God miraculously gave salvation to the city of Prague, so that the enemy, defeated in that place, did not again attempt to attack the city in this way, as will appear below.",
  "note": "A year after the defenestration the king's familiar is 'captain of the Taborites'. The crusaders held Prague Castle and Vyšehrad; Vítkov, the long hill east of the Old Town, would have been the third grip on the city, closing the road by which supplies came in."},
 {"pg": "387–388",
  "titel": "The battle on the hill, 14 July 1420",
  "orig": "Item in crastino, scilicet die dominico post Margarethe proximo, quasi hora vesperorum aptus fuit omnis regis exercitus, ut quidam ex eis in pluribus millibus ligneum in monte iuxta patibulum per Ziskam erectum propugnaculum expugnando invaderent, quo habito cetere turme secundum capitaneorum disposicionem in Pragensem in tribus locis irruerent civitatem [...]. Misnenses vero cum suis et sibi VII vel VIII millibus iunctis equestres montem ascendunt et cum impetu et tubicenis pretactum ligneum invadunt propugnaculum fossatam et turrim vinee obtinentes. Et cum murum ex terra et lapidibus factum vellent ascendere, due mulieres cum una virgine et forte cum XXVI viris, qui pro tunc in propugnaculo remanserant, viriliter lapidibus et cuspidibus resistentes defendebant, telis enim et pixidum pulvere carentes. Una itaque ex pretactis mulieribus, licet inermis, virorum vincebat animum nolens a loco suo pedem retrahere: „Antichristo, inquit, non licet fideli christiano cedere.“ Et sic animose pugnans interfecta spiritum exalavit. Ziska quoque veniens et ipse prostratus fuisset, nisi sui cum trituris eum de hostium manibus eruissent. Et cum iam tota quasi civitas de perdicione formidaret, oraciones et lacrimas cum parvulis fundens solum auxilium de celo prestolabatur, advenit interim presbiter cum corporis Christi sacramento et post eum quinquaginta forte sagittarii et ceteri rustici inermes cum trituris et inimici viso sacramento et audito campanule sono magnoque populi clamore vehementi timore prostrati terga vertunt cicius fugientes, alter alterum cupiens in cursu prevenire. [...] Quo facto rex cum omni exercitu silenter ad tentoria rediit ira, tedio, planctu et dolore repletus. Pragenses vero flexis in campo Hospitalensi genibus grates deo persolvunt Te deum laudamus altis vocibus personantes, quia non robore eorum, sed miraculose in paucis eis de hostibus dedit victoriam.",
  "en": "Item, on the next day, that is the Sunday after St Margaret, at about the hour of vespers, the whole of the king's army was ready: some thousands of them were to storm the wooden strongpoint built by Žižka on the hill by the gallows, and when it was taken the other troops, as the captains had arranged, were to fall on the city of Prague in three places [...]. The Meisseners with their men, and seven or eight thousand horsemen joined to them, climbed the hill and with a rush and trumpets attacked the said wooden strongpoint, taking the ditch and the tower of the vineyard. And when they tried to climb the wall made of earth and stones, two women with a girl and perhaps twenty-six men, who had stayed in the strongpoint at that moment, defended it manfully, resisting with stones and spears, for they had no arrows and no powder for their guns. One of these women, though unarmed, surpassed the courage of men, refusing to draw her foot back from her place: 'A faithful Christian,' she said, 'must not yield to Antichrist.' And so, fighting bravely, she was killed and breathed out her spirit. Žižka too, coming up, would himself have been struck down if his men had not rescued him from the enemy's hands with their flails. And when the whole city was already in fear of its ruin, pouring out prayers and tears with its children and waiting only for help from heaven, there came a priest with the sacrament of the body of Christ, and after him perhaps fifty archers and other unarmed peasants with flails; and the enemy, seeing the sacrament and hearing the sound of the little bell and the great shout of the people, were overcome with violent fear, turned their backs and fled, each wanting to outrun the other. [...] When this was done, the king returned silently with his whole army to the tents, full of anger, weariness, lamentation and grief. And the Praguers, kneeling in the field of the Hospital, gave thanks to God, singing the Te Deum with loud voices, because not by their strength but miraculously he had given them, few as they were, the victory over their enemies.",
  "note": "14 July 1420. The Czech translation in the same edition reads sixteen men for Laurence's twenty-six. The flail, the peasant's threshing tool shod with iron, is the weapon of the day; the companion site follows it into Žižka's field armies. The cut tells of the crusaders falling from the steep rock in their flight, about three hundred killed within an hour. The next page says the hill was afterwards called Žižka's hill, after its founder, or the Hill of the Chalice; the district of Prague on its slope is still Žižkov."},
]

ARTICLES = [
 {"pg": "390–391",
  "titel": "'By death or by life': the preamble, and the first article",
  "orig": "Item post predictam Theutonicorum factam inopinatam stragem quievit Praga civitas a frequenti hostium impulsu et non iam hus! hus! kacer! kacer! Theutonici proclamabant [...]. Ad que civitatis tractatores aiunt, se non posse sine consensu aliarum civitatum, cum quibus sunt ligati, aliquam inire concordiam, sed supplicant, quatenus propter ipsorum et regni tocius honorem apud regem publicam magistris et presbiteris obtineant audienciam, ut quatuor linguis, boemico, theutonico, hungarico et latino, valeant aperte veritates quatuor articulorum, pro quibus se Pragenses cum sibi adherentibus regi opponunt, lucide et aperte scripturis toti exercitui declarare [...]. Quapropter magistri Pragenses conscriptis IV articulis cum eorum probacionibus in latino, theutonico et boemico, ad exercitum direxerunt sub hac, que sequitur, forma: Nos magister civium, consules et scabini totaque communitas civitatis Pragensis capitalis regni Bohemie nostro et aliorum fidelium huiusmodi regni nomine instituimus etc. Notum sit universis Christi fidelibus, quod fideles in regno Boemie instant et domino iuvante instare proponunt sive per mortem, sive per vitam, quantum est eis possibile, pro articulis infrascriptis: Primo, quod verbum dei per regnum Bohemie libere et sine impedimento ordinate a sacerdotibus domini predicetur et nuncietur iuxta sentenciam salvatoris Marci ultimo: euntes in mundum universum predicate evangelium omni creature; et Mathie ultimo. Nam secundum apostolum verbum domini non est alligatum, sed orandum est secundum eundem, ut sermo dei currat et clarificetur ubique, ut dicitur IIa ad Thessal. III°. Et loqui linguis in ecclesia dei nemo debet prohiberi, ut dicitur prima ad Corinth. XIV°.",
  "en": "Item, after the unexpected slaughter of the Germans, the city of Prague rested from the frequent assaults of the enemy, and the Germans no longer shouted 'Hus! Hus! Kacer! Kacer!' [...] To which the city's negotiators said that they could make no agreement without the consent of the other towns with which they were bound, but they begged that, for their own honour and that of the whole kingdom, a public hearing before the king be obtained for the masters and priests, so that in four languages, Czech, German, Hungarian and Latin, they might set out plainly and clearly from the scriptures to the whole army the truths of the four articles for which the Praguers and those who adhered to them opposed the king [...]. Therefore the masters of Prague wrote down the four articles with their proofs in Latin, German and Czech and sent them to the army in the following form: We, the burgomaster, councillors and aldermen and the whole community of the city of Prague, capital of the kingdom of Bohemia, in our name and that of the other faithful of this kingdom, declare etc. Be it known to all the faithful of Christ that the faithful in the kingdom of Bohemia stand, and with the Lord's help intend to stand, by death or by life, as far as they are able, for the articles written below. First, that the word of God be preached and proclaimed freely and without hindrance, in good order, by the priests of the Lord throughout the kingdom of Bohemia, according to the saying of the Saviour in the last chapter of Mark: 'Go into all the world and preach the gospel to every creature'; and the last chapter of Matthew. For according to the apostle the word of God is not bound, but we must pray, as he says, that the word of God may run and be glorified everywhere (2 Thessalonians 3). And no one should be forbidden to speak in tongues in the church of God (1 Corinthians 14).",
  "note": "The Four Articles of Prague, the common programme of the Hussite parties, in the form sent to the crusading army in July 1420. The hearing was promised and never held: the cut tells how the barons on the king's side quarrelled over hostages until the talks lapsed. Free preaching is the first article because the conflict had begun with it: the ban of 1410 on preaching in chapels such as Hus's Bethlehem Chapel, which Hus defied."},
 {"pg": "391",
  "titel": "The second article: the chalice",
  "orig": "Secundo, quod sacramentum divinissime eukaristie sub utraque specie, scilicet panis et vini, omnibus Christi fidelibus nullo peccato mortali indispositis libere ministretur iuxta sentenciam et institucionem salvatoris, qui dixit: accipite et comedite, hoc est corpus meum, et bibite ex hoc omnes, hic est sanguis meus novi testamenti, qui pro multis effundetur Mathie XXVI°, Marci XIV°, Luce XXII°, ubi datur eciam preceptum apostolis, cum dicitur: hoc facite. [...]",
  "en": "Second, that the sacrament of the most divine Eucharist be given freely under both kinds, that is bread and wine, to all the faithful of Christ not disqualified by mortal sin, according to the word and institution of the Saviour, who said: 'Take and eat, this is my body; and drink of this, all of you, this is my blood of the new testament, which shall be shed for many' (Matthew 26, Mark 14, Luke 22), where a command is also given to the apostles in the words: 'Do this.' [...]",
  "note": "The chalice for the laity was not Hus's own cause: his friend Jakoubek of Stříbro began to give it in Prague in the autumn of 1414, while Hus was at Constance, and the council forbade it in June 1415. It became the sign of the movement, on banners, shields and church fronts. The cut is a page and a half of authorities, from the Gospel of John and Pope Gelasius to Thomas Aquinas."},
 {"pg": "393",
  "titel": "The third article: no lordship for the clergy",
  "orig": "Tercio, quod dominium seculare super diviciis et bonis temporalibus, quod contra preceptum Christi clerus occupat in preiudicium sui officii et dampnum brachii secularis, ab ipso auferatur et tollatur et ipse clerus ad regulam evangelicam et vitam apostolicam, qua Christus vixit cum suis apostolis, reducatur iuxta sentenciam salvatoris Mathie X° dicentis: et convocatis XII apostolis suis misit eos precipiens et dicens: nolite possidere aurum neque argentum neque pecuniam in zonis vestris. Et Mathie XX°: principes gencium dominantur eorum et, qui maiores sunt, potestatem exercent in eos; non ita erit inter vos. [...]",
  "en": "Third, that the secular lordship over riches and temporal goods which the clergy holds against the command of Christ, to the prejudice of its office and the damage of the secular arm, be taken and removed from it, and that the clergy itself be brought back to the rule of the gospel and the apostolic life which Christ lived with his apostles, according to the saying of the Saviour in Matthew 10, who, having called his twelve apostles, sent them out, commanding and saying: 'Possess neither gold nor silver nor money in your purses.' And Matthew 20: 'The princes of the nations lord it over them, and those who are greater exercise power over them; it shall not be so among you.' [...]",
  "note": "The article that served the nobility best: in the following years lords and towns took much of the Church's land. It echoes Jerome's account of Hus before the council, the patrimony of the churches owed to the poor and squandered on pomp (Poggio [5]), and, further back, the Franciscan argument about apostolic poverty. The cut piles up proof-texts from both Testaments, the canons and St Bernard."},
 {"pg": "394",
  "titel": "The fourth article: public sins to be punished",
  "orig": "Quarto, quod omnia peccata mortalia et specialiter publica alieque deordinaciones legi dei contrarie in quolibet statu rite et racionabiliter per eos, ad quos spectat, prohibeantur et destruantur. Que qui agunt, digni sunt morte, non solum qui ea faciunt, sed qui consenciunt facientibus, ut sunt in populo fornicaciones, comessaciones, furta, homicidia, mendacia, periuria, artes superflue, dolose et supersticiose, questus avari, usure et cetera hiis similia. In clero autem sunt simoniace hereses et exacciones pecuniarum a baptismo, a confirmacione, a confessione, pro eukaristie sacramento, pro sacro oleo, a matrimonio [...], pro prebendis et beneficiis, pro prelaciis, dignitatibus, personatibus, palliis et empcionibus et vendicionibus indulgenciarum et alie innumere hereses, que ex hiis oriuntur et polluunt ecclesiam Christi [...].",
  "en": "Fourth, that all mortal sins, and especially public ones, and other disorders contrary to the law of God, in every estate, be forbidden and destroyed duly and reasonably by those whose office it is. Those who do such things are worthy of death, not only those who do them but those who consent to those who do them: such as, among the people, fornication, gluttony, theft, murder, lies, perjury, superfluous, deceitful and superstitious crafts, greedy gain, usury and the like. Among the clergy, the simoniac heresies and the exaction of money for baptism, for confirmation, for confession, for the sacrament of the Eucharist, for the holy oil, for marriage [...], for prebends and benefices, for prelacies, dignities, parsonages, palls, and the buying and selling of indulgences, and the countless other heresies that spring from these and pollute the Church of Christ [...].",
  "note": "The broadest article, and the most dangerous: it hands the punishment of public sin to 'those whose office it is', and the radicals could read that as a licence for themselves. The list of the clergy's charges begins with the sacraments and ends with indulgences, where Hus's open break with Rome had begun in 1412. 'Worthy of death' is Paul's phrase (Romans 1:32). The cuts shorten the list of fees and the closing exhortation."},
]

CROWN = [
 {"pg": "396",
  "titel": "A king crowned in a castle",
  "orig": "Item XXVIII die Julii, dominico die scilicet post Jacobi, hora XII rex Sigismundus in castro Pragensi presentibus non omnibus baronibus nec scabinis Pragensibus in regem Boemie coronatur, facitque ibidem multos novos milites nullum penitus actum militarem prius pro communi bono ostendentes. Et sic a vulgo non veri, sed depicti milites sunt nuncupati. Item eodem die coronacionis sinistre et sequenti rex Sigismundus receptis ecclesie Pragensis et cenobii sancti Georgii capitibus, manibus, monstranciis, ceterisque de auro vel argento clenodiis concutere iubet et stipendia prebet promittens meliora facere, dum deus dederit regno pacem et quietem. Quorum igitur peccatum gravius, eorum scilicet, qui ligneas, aut eorum, qui argenteas ymagines destruxerunt? Item XXX die Julii, qui fuit tercius dies post regis coronacionem, totalis exercitus combustis tentoriis de campo recedit, regi Sigismundo velud hereticorum fautori et deceptori turpiter maledicentes.",
  "en": "Item, on the 28th day of July, that is the Sunday after St James, at the twelfth hour, King Sigismund was crowned king of Bohemia in Prague Castle, not all the barons being present, nor the aldermen of Prague; and there he made many new knights who had never shown any knightly deed for the common good. And so the people called them not true but painted knights. Item, on the same day of the ill-omened coronation and the next, King Sigismund took the heads, hands and monstrances and the other jewels of gold and silver of the church of Prague and of the convent of St George, had them broken up and paid his soldiers with them, promising to make better ones when God should give the kingdom peace and quiet. Whose sin, then, is the graver: theirs who destroyed images of wood, or his who destroyed images of silver? Item, on the 30th day of July, the third day after the king's coronation, the whole army burned its tents and left the field, cursing King Sigismund shamefully as a patron and deceiver of heretics.",
  "note": "Sigismund was crowned in St Vitus's cathedral inside the castle, which his garrison held, by Archbishop Conrad of Vechta, while the city below stood against him. The 'heads and hands' are the reliquaries of the cathedral and of St George's convent: the king who led a crusade against image-breakers melted down the saints to pay his army. On 2 September 1415 the lords had called him their heir and hoped him innocent (Protest [2]); in July 1420 the Praguers would not have him, and his own crusaders cursed him as a friend of heretics. He held the crown and not the kingdom: Bohemia accepted him only in 1436, a year before his death."},
]

SECTIONS = [
    {"id": "y1419", "zk": "Laur. 1419", "titel": "1419: Tábor, the town hall, the king's death, the first war in Prague",
     "blurb": "The year the movement became a revolt: forty thousand at communion on a mountain they called Tábor, the New Town councillors thrown from the town hall by the people and Jan Žižka, King Wenceslas dead within three weeks, images broken and the Charterhouse burned, Žižka at Vyšehrad, the fighting in the Lesser Town and the truce of St Brice.",
     "units": Y1419},
    {"id": "y1420", "zk": "Laur. 1420", "titel": "Winter and spring 1420: Plzeň, Sudoměř, Tábor",
     "blurb": "The radicals' five cities of refuge and Žižka at Plzeň, the killings in the shafts of Kutná Hora, the crusade proclaimed at Breslau, the battle of Sudoměř behind the wagons, Prague's oath to the chalice, Tábor's four captains, and the burgrave who changes sides.",
     "units": Y1420},
    {"id": "vitkov", "zk": "Laur. Vítkov", "titel": "The crusade before Prague and the battle of Vítkov",
     "blurb": "All Christendom before one city, 'Hus! Hus! Heretic!' shouted from the hill, Žižka's log fort on Vítkov, and the battle of 14 July 1420 won with stones, flails and the sacrament.",
     "units": VITKOV},
    {"id": "articles", "zk": "Laur. Articles", "titel": "The Four Articles of Prague",
     "blurb": "The programme sent to the crusading army in July 1420, in Latin, German and Czech: free preaching, the chalice, no worldly lordship for the clergy, and the punishment of public sins.",
     "units": ARTICLES},
    {"id": "crown", "zk": "Laur. Crown", "titel": "The coronation, 28 July 1420",
     "blurb": "Sigismund crowned in the castle while Prague held out, the reliquaries melted for soldiers' pay, and the crusade leaving the field cursing its own commander.",
     "units": CROWN},
]
