"""The Decree of Kutná Hora (1409) and the quarrel over it, from František
Palacký, Documenta Mag. Joannis Hus vitam, doctrinam, causam in Constantiensi
concilio actam ... illustrantia (Prague: Tempsky, 1869), nos. 10, 12, 13 and
15, pp. 347-359.

Internet Archive documentamagjoa00palagoog (printed page n = leaf n+20).
The OCR was used to find the places; every excerpt was read against the page
images. Palacký's text is kept with his spelling and his brackets; his
superscript abbreviations for the king's titles (V^ra Ser^tas and the like)
are written out. Cuts are marked [...].
English: the site's working translation (CC0).

Each unit: pg (Palacký page), titel, orig, en, note."""

MANDATE = [
 {"pg": "347–348",
  "titel": "Three votes for the Bohemian nation",
  "orig": "Wenceslaus dei gratia Romanorum rex semper Augustus et Bohemiae rex. Honorabiles, dilecti, devoti! Quamquam omnium hominum commodis intendere generaliter teneamur, non tamen eisdem in tantum debemus favere sollicite, ut eorum forsan, qui, pro locorum et temporum vel aliquarum aliarum rerum opportunitatibus constricti, nobis quadam sorte junguntur, dispendiis subjaceant et jacturae. Nam etsi omnem hominem omnis teneatur homo diligere: restat tamen, ut haec ipsa dilectio ex ordinata solummodo proveniat caritate; propter quod extraneum propinquo in amore praefigere, ordinatae caritatis est praeposteratio, cum verus amor semper incipiat a se ipso, et per consequens in posteros per proximitatis lineam derivetur. Cum itaque natio Teutonica, jure incolatus regni Bohemiae prorsus expers, in singulis universitatis studii Pragensis agibilibus, ut relatio veridica ad nos deduxit, tres voces sibi vendicavit ad usum, natioque Bohemica, ejusdem regni justa heres, tantummodo una gaudeat et fruatur: nos vero iniquum et valde indecens arbitrantes, ut de profectu incolarum, quibus recta competit successio, exteri et advenae abundanter affluant, et illi defectuum incommodis sentiant se oppressos: mandamus vobis praesentium virtute firmiter et districte, omnino habere volentes, quatenus mox visis praesentibus, contradictione et renitentia quibuslibet procul motis, nationem Bohemicam in singulis consiliis, judiciis, examinibus, electionibus et quibuscunque aliis actibus et dispositionibus universitatis praedictae, ad instar ordinationem, qua gaudet natio Gallica in universitate studii Parisiensis ac ceterae in Lombardia et Italia potiuntur nationes, ad tres voces admittere modis omnibus debeatis, sinentes eam vocum hujusmodi privilegio ex nunc in antea in perpetuum pacifice uti et gaudere; aliter non facturi, prout indignationem nostram gravissimam volueritis arctius evitare. Datum in Montibus Chutnis, die XVIII mensis Januarii, regnorum nostrorum anno Bohemiae quadragesimo sexto, Romanorum vero tricesimo tertio. Honorabilibus rectori et toti universitati studii Pragensis, devotis nostris dilectis.",
  "en": "Wenceslas, by the grace of God king of the Romans, ever Augustus, and king of Bohemia. Honourable, beloved, devoted! Although we are bound in general to attend to the advantage of all men, we ought not to favour them so anxiously that those who, constrained by the circumstances of places and times or of other things, are joined to us by a kind of lot should perhaps suffer loss and damage. For though every man is bound to love every man, it remains that this love should proceed only from ordered charity; and so to set the stranger before the neighbour in love is a reversal of ordered charity, since true love always begins from itself and from there flows on to others along the line of nearness. Since, then, the German nation, which has no right of native residence in the kingdom of Bohemia at all, has, as a truthful report has brought to us, claimed for its use three votes in all the business of the university of Prague, while the Bohemian nation, the rightful heir of the same kingdom, has and enjoys only one: we, judging it unjust and most unfitting that foreigners and newcomers should abound in what profits the natives, to whom the succession rightly belongs, while these feel themselves oppressed by want, command you by these presents firmly and strictly, and will it absolutely, that as soon as you have seen these presents, setting aside all contradiction and resistance, you are by all means to admit the Bohemian nation to three votes in all councils, judgments, examinations, elections and any other acts and dispositions of the said university, after the pattern of the ordinance which the French nation enjoys in the university of Paris and the other nations possess in Lombardy and Italy, allowing it from now on for ever to use and enjoy this privilege of votes in peace; and you will not do otherwise, as you wish the more surely to avoid our gravest displeasure. Given at Kutná Hora, on the 18th day of the month of January, in the forty-sixth year of our reign in Bohemia and the thirty-third as king of the Romans. To the honourable rector and the whole university of Prague, our devoted and beloved.",
  "note": "Issued at Kutná Hora (Kuttenberg, 'Montes Chutni'), the silver-mining town east of Prague. Charles IV had founded the university in 1348 with four 'nations', Bohemian, Bavarian, Polish and Saxon, each with one vote; the last three were mostly German-speaking, and the king's letter counts them as one 'German nation'. Behind the decree stood church politics: Wenceslas wanted the university to back his withdrawal of obedience from Gregory XII and the council of Pisa, which the Bohemian masters supported and the others did not. The argument of the preamble is that love is ordered, and begins with the neighbour. Palacký notes that the letter was entered into the university's statute book on 27 September 1409."},
]

NATIONS = [
 {"pg": "351–352",
  "titel": "The three nations petition the king",
  "orig": "Nunc vero Serenitas Vestra ad universitatem filiam vestram quandam literam destinavit, — ex cujus vel quorum inductione, deus novit, — in qua seriose mandatur, quod natio Bohemorum in singulis conciliis, judiciis, examinibus, electionibus et aliis actibus praefatae universitatis peramplius tres debeat habere voces, et aliae tres nationes saepedictae solum unam. Sed quia praescriptum mandatum istis tribus nationibus est multum grave et intolerabile, tendens in perpetuum interitum nationum earumdem, et si effectum sortiretur, infallibiliter sequeretur universitatis destructio, et praecipue trium nationum praescriptarum exterminatio: ideo Vestrae inclytissimae Dignitati supplicamus humillime toto cum affectu, quatenus praefatas tres nationes in suis consuetudinibus statutis, quae ab initio studii usque in praesentem diem de benigna ordinatione vestri progenitoris inclytissimi habuisse dinoscuntur, [...] gratiose conservetis. Quia salvis juramentis nostris et honoribus nequaquam ab istis valemus recedere [...]. Et nequaquam dubitamus, quando Serenitati Vestrae hoc constiterit, quod ad talia mandata nos minime velit artare, cum in nulla universitate totius Alemanniae, nec in studio Parisiensi talia, quae ista mandata praetendunt, observentur. [...] Si vero natio Bohemorum reputat sibi esse praejudicium et gravamen, quod quaelibet aliarum trium nationum in vocibus sibi est aequalis in conciliis, judiciis, examinibus, electionibus et aliis actibus universitatis, si et in quantum est possibile, salvis juramentis et concordia inter eam et alias tres nationes factis, ex tunc dignetur Vestra Serenitas, ad quam solum spectat nobis de pace et concordia providere, eam ab aliis tribus nationibus dividere quoad ista et separare ita, quod ipsa habeat sua concilia, judicia, examina et electiones, et aliae tres nationes sua. Sic forsan domino concedente magis pacifice et quiete convivemus. [...] Dat. Pragae, in die S. Dorotheae, sub nationum trium, Polonorum, Bavarorum et Saxonum sigillis.",
  "en": "But now Your Serenity has sent to the university, your daughter, a letter (at whose prompting, God knows) in which it is earnestly commanded that the nation of the Bohemians shall henceforth have three votes in all councils, judgments, examinations, elections and other acts of the said university, and the other three nations so often named only one. But since this mandate is very heavy and intolerable to these three nations, tending to the perpetual ruin of the same nations, and if it took effect the destruction of the university would infallibly follow, and above all the extermination of the three said nations: therefore we most humbly beseech Your most illustrious Dignity with all our heart graciously to preserve the said three nations in their established customs, which they are known to have had from the beginning of the university to this day by the kind ordinance of your most illustrious father [...]. For saving our oaths and our honour we can in no way depart from them [...]. And we do not doubt that when this is made plain to Your Serenity, you will by no means wish to constrain us to such mandates, since in no university of all Germany, nor in the university of Paris, are such things observed as these mandates put forward. [...] But if the nation of the Bohemians thinks it a prejudice and a burden that each of the other three nations is its equal in votes in the councils, judgments, examinations, elections and other acts of the university, then, if and in so far as it is possible, saving the oaths and the concord made between it and the other three nations, may Your Serenity, to whom alone it belongs to provide for our peace and concord, deign to divide and separate it from the other three nations in these matters, so that it has its own councils, judgments, examinations and elections, and the other three nations theirs. So perhaps, the Lord granting, we shall live together more peacefully and quietly. [...] Given at Prague, on St Dorothy's day, under the seals of the three nations, the Poles, the Bavarians and the Saxons.",
  "note": "St Dorothy's day is 6 February 1409, less than three weeks after the decree. The masters of the three nations sign as the king's 'humble petitioners'. Their two arguments: the oaths every member had sworn to the statutes, and the practice of every other university, Paris included. Against the king's comparison with Paris they are right that each nation there had one vote; the decree's 'pattern of Paris' was a claim about the native nation's standing, not about its arithmetic. Their offer at the end, two universities in one, was not taken up."},
 {"pg": "352–353",
  "titel": "The oath to leave",
  "orig": "Ego N. promitto sine dolo et fraude nationibus Polonorum, Bavarorum et Saxonum, et cuilibet earum, et cuilibet personae de praefatis nationibus, sub istis quatuor poenis infrascriptis et qualibet earum, non obstante jure communi, quo cavetur, quod in poenis minor praejudicat majori, scil. perjurii, excommunicationis, privationis honoris et centum sexag., quod antequam permittam, quod natio Bohemorum in conciliis, judiciis, electionibus, examinibus et aliis dispositionibus et actibus universitatis Pragensis habeant tres voces et aliae tres nationes tantum unam, aut quod fiat quovis alio modo contra consuetudinem laudabilem hactenus observatam et ordinationem juratam, quod potius velim exire praefatam universitatem et nunquam ad eam causa studii redire; quia permissio istius est contra juramenta, quae feci universitati et tendit in destructionem universitatis et confusionem regni et regis; [...] quod si, quod absit, propter causam suprascriptam me ab universitate recedere oportet, quod non velim redire ad universitatem, nisi praefatae nationes in integrum restituantur in omnibus juribus et suis consuetudinibus, ita quod nullus fraudulose suo emolumento defraudetur.",
  "en": "I, N., promise without guile or fraud to the nations of the Poles, the Bavarians and the Saxons, and to each of them, and to each person of the said nations, under the four penalties written below and each of them (notwithstanding the common law which provides that among penalties the lesser prejudices the greater), namely perjury, excommunication, loss of honour and a hundred threescore [of groats], that before I allow the nation of the Bohemians to have three votes in the councils, judgments, elections, examinations and other dispositions and acts of the university of Prague and the other three nations only one, or allow anything to be done in any other way against the praiseworthy custom observed until now and the sworn ordinance, I will rather leave the said university and never return to it for the sake of study; because to allow this is against the oaths I made to the university, and tends to the destruction of the university and the confusion of the kingdom and the king; [...] and if, which God forbid, I must withdraw from the university for the cause written above, I will not return to the university unless the said nations are restored in full to all their rights and customs, so that no one is fraudulently deprived of his income.",
  "note": "Undated; Palacký prints it from the same Leipzig manuscript as the petition. The cut lists the efforts the swearer will make with the princes of Bohemia and with King Wenceslas first. The oath was kept. When the decree was enforced in the spring of 1409, masters and students of the three nations left Prague in numbers that the sources put anywhere from several hundred to several thousand; many went to Leipzig, where a new university was opened in December 1409. Hus, chosen rector of the now Bohemian university in October, was afterwards blamed for the exodus; Palacký's no. 14, a damaged autograph, is his public denial."},
]

DEFENCE = [
 {"pg": "356",
  "titel": "'The head and not the tail'",
  "orig": "Septimo habetur, quod natio Bohemica debet esse rectrix praecipua nationum aliarum in universitate Pragensi. Patet hoc primo a simili ex lege divina. Nam Dominus (Deuteronom. 28) suo (populo) promittit dicens: „Si audieris mandata domini dei tui, quae ego praecipio tibi hodie &c., constituet te dominus deus tuus in caput et non in caudam, et eris semper supra et non subter.“ Et iterum: „Faciet te deus excelsiorem cunctis gentibus, quae versantur in terra.“ Si ergo deus suum populum obedientem in caput posuit, excelsiorem cunctis gentibus fecit, ergo a simili rex Bohemiae nationem Bohemicam, quae est populus suus obediens, potest, imo debet ponere in caput et non in caudam, ut esset supra semper et non subter; sequitur, quod natio Bohemica regi obediens debet esse in terra Bohemiae cunctis aliis excelsior, et debet (esse) in caput et non in caudam, semper supra et non subter; et per consequens natio Bohemica debet esse rectrix praecipua nationum aliarum in universitate studii Pragensis, posita con... stantia universitatis et nationibus in illa conjunctis (sic).",
  "en": "Seventh, it follows that the Bohemian nation ought to be the chief ruler of the other nations in the university of Prague. This is shown first by analogy from the divine law. For the Lord (Deuteronomy 28) promises his (people), saying: 'If thou wilt hearken to the commandments of the Lord thy God, which I command thee this day, etc., the Lord thy God will make thee the head and not the tail, and thou shalt be always above and not beneath.' And again: 'God will make thee higher than all the nations that are on the earth.' If then God set his obedient people at the head and made it higher than all nations, then by analogy the king of Bohemia can, indeed must, set the Bohemian nation, which is his obedient people, at the head and not at the tail, so that it is always above and not beneath. It follows that the Bohemian nation, obedient to the king, ought to be higher than all others in the land of Bohemia, and ought to be the head and not the tail, always above and not beneath; and consequently the Bohemian nation ought to be the chief ruler of the other nations in the university of Prague, given the continuance of the university and the nations joined in it (sic).",
  "note": "Palacký prints the 'Defence of the royal mandate' from a contemporary manuscript then at the Benedictine abbey of Břevnov. It is anonymous and written from the Bohemian side of the university; its conclusions are numbered like a disputation. The proof-text from Deuteronomy, 'the head and not the tail', runs through the whole piece. The gap 'con...stantia' is in Palacký's manuscript."},
 {"pg": "357",
  "titel": "'In Vienna or Heidelberg'",
  "orig": "Item lex est naturae: „quod tibi fieri non vis, aliis ne feceris ipse,“ et „quod vis tibi fieri, alii tu feceris ipse.“ Et natio Teutonica nollet sibi fieri, quod natio Bohemica esset excelsior in Vienna vel Helberga, et quod natio Bohemica esset ibi in caput et semper supra; et iterum natio Teutonica vellet sibi fieri, quod ipsa foret excelsior natione Bohemica in Vienna vel Helberga: igitur ex prima parte non debet velle esse excelsior in Bohemia, nec in caput, nec semper supra; et ex secunda parte debet velle, quod natio Bohemica in terra Bohemiae sit aliis excelsior nationibus, et sit in caput et non in caudam et semper supra et non subter. Confirmavit istud Salvator, dicens (Lucae VI): „Prout vultis, ut faciant vobis homines, et vos facite illis.“ Si ergo volunt Teutonici, ut Bohemi, si essent in Teutonia, facerent sic, quod consilia eorum, voces et utilitates non tollerent et se supra et in caput non ponerent, faciant in Bohemia sic Bohemis.",
  "en": "Again, it is a law of nature: 'What you would not have done to you, do not do to others', and 'What you would have done to you, do to another.' And the German nation would not wish it done to them that the Bohemian nation should be higher in Vienna or Heidelberg, and that the Bohemian nation should there be the head and always above; and again the German nation would wish it done to them that they should be higher than the Bohemian nation in Vienna or Heidelberg. Therefore, from the first part, they ought not to wish to be higher in Bohemia, nor the head, nor always above; and from the second part they ought to wish that the Bohemian nation in the land of Bohemia should be higher than the other nations, and be the head and not the tail, and always above and not beneath. The Saviour confirmed this, saying (Luke 6): 'As you would that men should do to you, do you also to them likewise.' If then the Germans wish that the Bohemians, were they in Germany, would act so as not to take away their councils, votes and benefits, and not set themselves above them and at their head, let them do the same to the Bohemians in Bohemia.",
  "note": "'Helberga' is Heidelberg; its university (1386), like Vienna's (1365), was younger than Prague's and German in its masters. The golden rule is turned into an argument for the native nation's precedence in its own land. The passages that follow in the same text draw harsher conclusions about foreigners; the Defence is not a tolerant document, and the decree's opponents read it as the programme it was."},
 {"pg": "359",
  "titel": "'I am the truth, not the custom'",
  "orig": "Ad idem, scil. dissolutionem malae consuetudinis, est b. Augustinus de baptismo parvorum (et ponitur in canone, dist. VIII): „Dominus dicit in evangelio, ego sum veritas; non dixit, ego sum consuetudo; ita veritate manifesta, cedat consuetudo.“ Ecce praefert iste vir sanctus veritatem consuetudini. Sed cum veritas sit ex supradictis, quod Bohemi debent habere in Bohemia jus et praerogativam super extraneos, et esse in caput et non in caudam in consiliis et judiciis ceterisque actibus bonum et honorem regni Bohemiae concernentibus: igitur manifesta illa veritate, debet cedere illa consuetudo, qua extranei in regno Bohemiae jus Bohemorum occuparunt.",
  "en": "To the same point, namely the dissolving of a bad custom, there is blessed Augustine on the baptism of infants (and it is placed in the canons, distinction 8): 'The Lord says in the gospel, I am the truth; he did not say, I am the custom. So, when the truth is plain, let custom give way.' See how this holy man puts truth before custom. But since it is the truth, from what has been said, that the Bohemians ought to have right and precedence over foreigners in Bohemia, and to be the head and not the tail in councils and judgments and the other acts that concern the good and honour of the kingdom of Bohemia: therefore, that truth being plain, the custom by which foreigners in the kingdom of Bohemia have occupied the right of the Bohemians must give way.",
  "note": "The answer to the three nations' first objection, that long custom gave them their votes (KH Nations [1]). The maxim 'Christ said I am the truth, not I am the custom' came into Gratian's Decretum (D. 8) and was much quoted; here it overrides the oath to the statutes. The same move, from the custom of the Church to the truth of scripture, is the move of De ecclesia (De eccl. [4], [5])."},
]

SECTIONS = [
    {"id": "mandate", "zk": "KH Mandate", "titel": "The king's mandate, 18 January 1409",
     "blurb": "Wenceslas IV, from the mining town of Kutná Hora, orders the university of Prague to give the Bohemian nation three votes and the three other nations together one.",
     "units": MANDATE},
    {"id": "nations", "zk": "KH Nations", "titel": "The three nations refuse",
     "blurb": "The Polish, Bavarian and Saxon nations petition the king on 6 February 1409, and bind themselves by oath to leave Prague rather than accept the decree.",
     "units": NATIONS},
    {"id": "defence", "zk": "KH Defence", "titel": "A defence of the decree",
     "blurb": "An anonymous Bohemian disputation for the king's mandate: the native nation as 'the head and not the tail', the golden rule turned on the Germans, and truth set above custom.",
     "units": DEFENCE},
]
