"""Letters of Jan Hus from Constance, 1414-1415.

Original (Latin or Czech): František Palacký, Documenta Mag. Joannis Hus
(Prague: Tempský, 1869), nos. 41, 59, 70, 75, 83 and 88, pp. 78-144.
Internet Archive documentamagjoa00palagoog (printed page n = leaf n+20).

English: The Letters of John Hus, translated by Herbert B. Workman and
R. Martin Pope (London: Hodder and Stoughton, 1904), letters XXXVIII, LII,
LXIII, LXVIII, LXXIV and LXXIX, pp. 160-270. Internet Archive
lettersofjohnhus00husjuoft (printed page n = leaf n+36). Public domain.

Both read against the page images. Palacký's spelling is kept (the old Czech
orthography with w for v); Workman and Pope's English is kept as printed,
with their own bracketed insertions and without their footnote numbers.
Cuts, the same in both columns, are marked [...].

Each unit: pg (Palacký page; Workman-Pope page), titel, lang, orig, en, note."""

LETTERS = [
 {"pg": "78–79 (W-P 160–161)", "lang": "la",
  "titel": "Arrived at Constance",
  "orig": "Salus a Christo Jesu. Carissimi! Scitote, quia bene sto per omnia. Veni sine salvo conductu papae ad Constantiam: rogetis ergo deum, ut det mihi constantiam, quia multi adversarii et fortes insurgunt contra me, quos praesertim concitat venditor indulgentiarum Pataviensis decanus, jam praepositus, et Michael de Causis, qui semper annectit processus contra me. Sed nihil horum timeo nec vereor, sperans, quod post magnam pugnam magna sit victoria, et post victoriam majus praemium et major confusio persequentium. Papa non vult tollere processus, et dixit: quid ego possum? tamen vestri faciunt. Sed locuti sunt duo episcopi et unus doctor cum D. Joanne Kepka, quod ego sub silentio concordarem. Et sic cognosco, quod timent meam publicam responsionem et praedicationem, quam spero de dei (gratia) consequar, dum rex Sigismundus affuerit. De quo mihi nuntiavit D. Wenceslaus de Lestna, quod valde fuit gavisus, quando ipse nobilis D. Wenceslaus dixit sibi, quod equito directe ad Constantiam sine salvo conductu. In omnibus civitatibus bene stetimus, honorati sumus, et intimationes apposuimus latinas et teutonicas in civitatibus imperialibus, in quibus habui collationes cum magistris. Et habui unum praecursorem, episcopum Lubucensem, qui uno nocturno nos semper praecessit, et divulgavit, quod me ducerent catenatum in curru, et quod caverent me, quia ego cognoscerem mentes hominum. Et sic, quando propinquavimus alicui civitati, occurrebant turbae quasi ad spectaculum. Sed confusus est inimicus mendacio, et populus gratus fuit, quando audivit veritatem. Certe Christus Jesus est mecum tamquam bellator fortis; ideo non timeo, quid faciat inimicus. Vivatis sancte, oretis devote, ut dominus misericors assistat mihi, defendens in me finaliter legem suam. Datum in nocte, in die s. Leonardi.",
  "en": "Greetings from Christ Jesus! Dear friends, I am quite well through it all. I came without the Pope's safe-conduct to Constance; pray God then that He may grant me constancy, because many powerful adversaries have risen up against me, stirred up in particular by that seller of indulgences, the Dean of Passau, now the head of the chapter there, and Michael de Causis, who is always posting up writs against me. But I fear none of these things, nor am I affrighted, for I hope that a great victory is to follow a great fight, and after the victory a greater reward, and the greater confusion of my persecutors. The Pope is unwilling to quash the writs. He said, \"What can I do? your side are the aggressors.\" But two bishops and a doctor had some talk with Baron John Kepka [Chlum] to the effect that I should come to terms under a pledge of silence. By which I apprehend that they are afraid of my public reply and sermon, which I hope by the grace of God to deliver when Sigismund comes. Of the latter Baron Wenzel de Lestna has sent news that he expressed pleasure when he (the noble Baron Wenzel) told him that I was riding direct to Constance without safe-conduct. In all the cities we were well treated and had respect paid to us, while we posted up notices in Latin and German in the free cities where I had interviews with the magistrates. I had a herald on the journey in the Bishop of Lebus, who was always one night ahead of us. He spread the news abroad that they were conducting me in a cart in chains, and that people must beware of me, as I could read men's thoughts! So whenever we drew near a city, out came the crowds to meet us, as if to a show! But the enemy was put to confusion by his lie, while the people were glad when they heard the truth. Surely Christ Jesus is with me as a strong warrior; therefore I fear not what the enemy may do. Live holy lives, and pray earnestly that the Lord in His mercy may help me and defend His law in me to the end. Sent off on the evening of St. Leonard's Day.",
  "note": "6 November 1414, three days after his arrival. The play on Constantia and constantia is Hus's own. He rode 'without safe conduct' because Sigismund's letter (Mlad. Journey [1]) had not yet reached him; the pope's own safe conduct he never had. Workman and Pope's note: only the pope's could have protected him from the inquisition, since the king's did not reach the spiritual sphere. 'John Kepka' is Jan of Chlum's nickname."},
 {"pg": "100 (W-P 201)", "lang": "la",
  "titel": "'All my gaolers are taking to flight'",
  "orig": "Jam custodes mei omnes recedunt, nec habebo quod manducem, et nescio quid mihi continget in carcere. Rogo, accedatis cum aliis dominis regem, ut faciat aliquem finem mecum, ne habeat et peccatum et confusionem de me. Item rogo, quod veniatis ad me cum dominis Bohemis, quia necessarium est me loqui vobiscum. Nobilis D. Joannes cum D. Wenceslao et cum aliis, accedatis cito D. Regem, quia periculum est in mora, itaque necesse est, ut fiat primo quoque tempore. Cetera, quae a vobis desiderem, cito et bene intelligite. Vereor, ne me secum auferat magister aulae papisticae noctu; nam hodie manet in monasterio. Episcopus Constantiensis misit ad me literas, significans, se nihil velle negotii mecum habere. Idem fecerunt cardinales. Si diligitis miserum Anserem, provideatis, ut rex de sua curia det custodes, vel liberet me de carcere hoc vespere. Datum in carcere, Domine ne longe, dominico die sero.",
  "en": "All my gaolers are now taking to flight. I have nothing to eat and I don't know what is going to happen to me in prison. Please go with the other nobles to the King and get him to take some final steps in my case, lest he fall into sin and confusion on my account. Please also come to me with the Bohemian nobles, for I must have a word with you. Noble Baron John and Baron Wenzel and the rest of you, make haste and see my lord the King. There is danger in delay. It is so urgent that it should be done at once. Think carefully and quickly of the other things I want from you. I am afraid that the master of the Pope's household will carry me off with him by night; for to-day he has been hanging about the monastery. The Bishop of Constance hath sent letters to me hinting that he wishes to have no responsibility for me. The cardinals have done the same. If you love your poor Goose, get the King to send me guards from his own court or to set me free from prison this very evening. Written in prison (note the introit of the day, \"O Lord, make no long tarrying\") late on Sunday night.",
  "note": "24 March 1415, Palm Sunday, four days after Pope John XXIII had fled from Constance. Hus was held in the Dominican convent under the pope's guards, who followed their master. 'Husa' is Czech for goose; he signs himself Anser. Sigismund did not set him free: he had him handed to the bishop of Constance, who took him to the castle of Gottlieben."},
 {"pg": "114–115 (W-P 229–230)", "lang": "la",
  "titel": "'As little to be trusted as in the matter of the safe-conduct'",
  "orig": "Rogo adhuc propter deum, quod omnes domini congregati petant regem pro finali audientia, quia ex quo solus dixit in concilio, quod in proximo audientia dabitur mihi, ut respondeam in scripto breviter: confusio sua magna erit, si illud dictum praeteribit. Sed aestimo, quod suum dictum est tam stabile, sicut de salvo conductu, de quo dixerunt mihi in Bohemia, quod caverem a suo salvo conductu. Et alii dixerunt: ‚Ipse te dabit inimicis.‘ Et D. Mikeš Diwoky dixit mihi coram magistro Jesenicz: ‚Magister! scias pro certo, quod condemnaberis.‘ Aestimo, quod ille scivit intentionem regis. Aestimabam, quod saperet sibi lex dei et veritas; modo concipio, quod non multum sibi sapit; prius me condemnavit, quam inimici mei. Si saltem tenuisset modum gentilis Pilati, qui auditis accusationibus, dixit: „Nullam causam invenio in hoc homine;“ vel saltem si dixisset: „Ecce ego dedi sibi salvum conductum; si ergo ipse non vult pati concilii decisionem, ego remittam eum regi Bohemiae cum sententia vestra et attestationibus, ut ipse cum suo clero ipsum dijudicet,“ quia sic mihi intimavit per Henricum Lefl et per alios, quod vellet mihi ordinare sufficientem audientiam, et si me non submitterem judicio, quod vellet me dirigere salvum vice versa.",
  "en": "I beg you for God's sake to get all the nobles to petition Sigismund in a body for a final hearing, because he was the only one in the Council to say that at the next hearing I should be allowed to reply briefly in writing. His confusion will be great if that promise is unfulfilled. But methinks his word is as little to be trusted as in the matter of the safe-conduct. They told me in Bohemia to beware of that safe-conduct. Others said, \"He will hand you over to your enemies.\" Lord Mikess Diwoky remarked to me in the presence of Master Jesenicz, \"Master, you may take it for certain that you will be condemned.\" I imagine he knew the King's intentions. I thought that God's law and truth would be his wisdom, only I fancy he has not much wisdom. He passed judgment upon me before my enemies did. If he had only held to the method of the Gentile Pilate who, on hearing the charges, said, \"I find no fault in this man\" or, at least, if he had said, \"I gave him a safe-conduct; if he doth not wish to abide by the decision of the Council, I will send him back to the King of Bohemia with your verdict and findings, in order that his Majesty, along with his clergy, may pass judgment on him\"! Indeed, he sent word to me by Lord Henry Lefl and others that he desired to arrange a satisfactory hearing for me, and if I did not accept the judgment he would send me back again in safety.",
  "note": "Written in the days after 8 June 1415, when Hus had learned what the king had said to the council after the last hearing (Mlad. Hearings [2]). Here is Hus's reading of the safe conduct: not a promise of a hearing only, but of a return to Bohemia if he would not submit. The king's reading is in Mlad. Hearings [1]. Jan of Jesenice was Hus's lawyer at Prague."},
 {"pg": "121–122 (W-P 238–239)", "lang": "la",
  "titel": "To the 'Father': why he cannot abjure",
  "orig": "Omnipotens pater sapientissimus et piissimus patri meo propter Christum Jesum favorose dignetur donare vitam gloriae sempiternam. Reverende pater! valde gratus sum de vestra pia et paterna gratia. Non audeo me juxta tenorem exhibitum concilio submittere, tum quia oporteret veritates multas condemnare, quas, ut ab ipsis audivi, vocant scandalosas; tum, quia oporteret me perjurium incidere ex abjuratione, confitendo, me errores tenuisse: ex quibus scandalizarem valde populum dei, qui a me in praedicatione audivit contrarium. Si ergo sanctus Eleazarus, veteris legis homo, de quo in Machabaeorum, noluit confiteri mendaciter, se comedisse carnes a lege prohibitas, ne contra deum faceret et ne posteris malum exemplum relinqueret: quomodo ego, sacerdos novae legis, licet indignus, propter timorem poenae, quae cito praeteribit, vellem transgredi, gravius peccando, legem dei? primo recedendo a veritate, secundo perjurium faciendo, et tertio proximos scandalizando. Revera expedit mihi magis mori, quam fugiendo poenam momentaneam, incidere in manus domini et forte post in ignem et obprobrium sempiternum. Et quia ad Christum Jesum potentissimum et justissimum judicem appellavi, sibi committens causam meam: ideo sto suae diffinitioni et sententiae, sciens, quia non juxta falsa testimonia, nec juxta erronea, sed juxta veritatem et merita unumquemque hominem judicabit.",
  "en": "May the Father Almighty, most wise and most loving, be pleased to grant to my \"Father,\" highly esteemed for Christ Jesus's sake, the everlasting life of glory. Reverend Father, I am truly grateful for your pious and fatherly kindness. I dare not submit myself to the Council in the terms you have suggested, because thereby I should have to condemn many truths which, as I have heard from their own lips, they call \"scandalous,\" and also because I should be guilty of perjury if I abjured and confessed that I have held erroneous views; and thereby I should greatly scandalise God's people who have heard the contrary in my preaching. If then the holy Eleazar, who lived under the old law, and of whom we read in Maccabees, refused to make a lying confession that he had eaten flesh forbidden by the law so as not to act against God's will and to leave an evil example to his descendants, how could I, a priest of the new law, albeit unworthy, for fear of a penalty which will soon be over, be guilty of the more grievous sin of breaking God's law? In the first place, I should err from the truth, in the second I should commit perjury, and thirdly I should be a stumbling-block to my neighbours. Assuredly it is fitting for me rather to die than to flee a momentary penalty to fall into the Lord's hand and afterwards, perchance, into everlasting fire and shame. And because I have appealed to Christ Jesus, the most potent and just of all judges, committing my cause to Him, therefore I stand by His judgment and sentence, knowing that He will judge every man not on false and erroneous evidence but on the true facts and merits of the case.",
  "note": "Mid-June 1415. The 'Father' was a member of the council, never named, who tried by letter to find a form of submission Hus could sign. Hus's three reasons are the whole logic of his refusal: to abjure articles he had not held would be to confess that he had held them (a lie under oath), and would scandalize those who had heard him preach the opposite."},
 {"pg": "131–133 (W-P 254, 257)", "lang": "cs",
  "titel": "'God will raise up braver men'",
  "orig": "Mistr Jan Hus, w naději slúha boží, wšem wěrným jenž boha a jeho zákon milují a budú milowati, žádost swú, aby w prawdě a w milosti božie přebýwali a do smrti statečně stáli. Nejmilejší! napomínám wás, abyste se nelekali, ani ustrašiti dali proto, že sú mé knihy k spálení odsúdili. Pomněte, žeť sú swatého Jeremiáše proroctwie, jež jest buoh kázal psáti, spálili, a wšak sú toho, což jest prorokowal, neušli, neb po spálení kázal jemu pán bóh túž řeč a ješče wiece přidaw, popsati. [...] Jistě již se zlost, ohawnost a hanba Antikristowa oznámila na papeži i na jiných w sboru; již wěrné slúhy boží mohú znamenati z řeči swého spasitele, co jest mienil, řka: „Když uzřiete ohawnost na miestě spustilém, jenž jest prorokowal Daniel; ktož čte, rozuměj.“ Ohawnost weliká jest pýcha, lakomstwie, swatokupectwie; na miestě spustilém, totiž w dóstojenstwie, jenž jest pusto od pokory a od jiných cností, jakož zřejmě widíme na těch, jenž držie úřad a dóstojenstwie. O by bylo lze popsati zlosti, aby wěrné slúhy se jich ostřiehali! Rád bych, ale ufám bohu, že dá jiné po mně statečnějšie, i že jsú nynie, jenž lépe oznámie zlost Antikristowu a nasadie swých žiwotów k smrti pro prawdu pána Jezu Krista, jenž dá wám i mně wěčnú radost, Amen. Psán list na sw. Jana Křtitele w žaláři w okowách w paměti tej, že Jan také w žaláři w okowách pro boží prawdu jest sťat.",
  "en": "Master John Hus, a servant of God in hope, to all the faithful who love and will love God and His law, praying that they may dwell in the truth, grow in the divine grace, and bravely persevere even unto death. Beloved, I exhort you not to be terrified, neither shaken with fear, because they (my enemies) have ordered my books to be burnt. Remember that the prophecies of the holy Jeremiah, which he wrote at God's command, were burnt, and yet the Jews did not escape the fate he had foretold; for after that they had been burnt, God bade him write the same words, and add to them besides many like words. [...] Surely now the wickedness, iniquity, and baseness of Antichrist has been revealed in the Pope and his associates in the Council: now the faithful servants of God can understand the meaning of the Saviour's words, When ye shall see the abomination of desolation which was spoken of by Daniel the prophet, ... he that readeth, let him understand. Verily \"a great abomination\" is pride, avarice, and simony: \"in a place apart\" — that is, dignity which lacks modesty, love, and other virtues; and this is what we clearly mark in those who win office and dignity. Would that I were allowed to point out their wickedness, in order that the faithful servants of God might beware of them! Gladly would I do so; but I am trusting that God will raise up others after me, braver men than there are to-day, who shall better reveal the wickedness of Antichrist and lay down their lives for the truth of the Lord Jesus Christ, who will grant eternal joy both to you and to me. Amen. I write this letter in prison, on the day of St. John Baptist, as I lie bound in chains, remembering that St. John also was beheaded in prison for the sake of God's truth.",
  "note": "24 June 1415, in Czech, to the faithful in Bohemia, after the council had ordered his books burned. The English after the cut begins on Workman and Pope's p. 257. The cut passage attacks the council that had deposed John XXIII for simony and murder, though many of its members had bought office from him. The last sentence was read in Bohemia as a prophecy."},
 {"pg": "143–144 (W-P 269–270)", "lang": "la",
  "titel": "'Sigismund hath acted deceitfully throughout'",
  "orig": "Gratiossimi benefactores mei et veritatis protectores! Hortor vos per viscera Jesu Christi, ut jam postpositis vanitatibus hujus seculi aeterno regi Christo domino militetis. Nolite confidere in principibus, in filiis hominum, in quibus non est salus, quia mendaces et fallaces filii hominum hodie sunt, cras peribunt, deus autem manet in aeternum, qui non ad sui indigentiam, sed ad suorum profectum habet servos, quibus quod promittit, tenet, quod dare spondet, implet, nullum per salvum conductum decipit, nullum a se fidelem servum removet, quia dicit: „Ubi ego sum, illic et servus meus erit.“ [...] Aestimo, quod ista est ultima ad vos litera, quia cras, ut aestimo, purgabor in spe Jesu Christi per diram mortem a peccatis. Quae mihi occurrebant ista nocte, non possum scribere. Sigismundus omnia dolose egit. Deus parcat sibi, et solum propter vos, et ipsi audivistis sententiam, quam tulit. Rogo, nullam habete suspicionem de Vito fideli.",
  "en": "Most gracious benefactors and guardians of the truth, I exhort you by the tender mercies of Jesus Christ to lay aside at once the vanities of this world and fight for the eternal King, even Christ the Lord. Put not your trust in princes, in the sons of men, in whom is no safety; for to-day the sons of men are liars and deceivers, and to-morrow they will perish; but God abideth for ever. He hath servants not because He is in need of them, but for their own welfare. What He promises to them, He holds to; what He pledges himself to grant, He fulfils; He deceives no man by a safe-conduct and dismisses no faithful servant; for He saith: Where I am, there shall My servant be also. [...] Methinks this is my last letter to you, for to-morrow I suppose I shall be cleansed from my sins in hope of Jesus Christ by a dreadful death. I cannot write of what I passed through last night. Sigismund hath acted deceitfully throughout. God spare him, and that only for your sakes; you yourselves heard the advice which he gave. I beg you to have no suspicion of the faithful Veit.",
  "note": "Undated; Palacký places it at the end of June 1415. To the two noblemen Sigismund had charged with bringing Hus to Constance. 'He deceives no man by a safe-conduct' is written against the king; 'you yourselves heard the advice which he gave' refers to Sigismund's words after the hearing of 8 June, which Chlum and Leštno overheard (Mlad. Hearings [2]). Veit (Vitus) was one of the friends who helped Hus at Constance."},
]

SECTIONS = [
    {"id": "constance", "zk": "Letters", "titel": "Letters from Constance (November 1414 – June 1415)",
     "blurb": "Six letters from the arrival to the eve of the end, in the original Latin or Czech from Palacký, with Workman and Pope's English of 1904: the journey without safe conduct, the flight of the gaolers, the king's word, the refusal to abjure, the books burned, and 'Sigismund hath acted deceitfully throughout'.",
     "units": LETTERS},
]
