"""Peter of Mladoňovice, Relatio de Mag. Joannis Hus causa in Constantiensi
concilio acta (1415), in František Palacký, Documenta Mag. Joannis Hus vitam,
doctrinam, causam in Constantiensi concilio actam et controversias de religione
in Bohemia annis 1403-1418 motas illustrantia (Prague: Tempský, 1869),
pp. 237-324.

Internet Archive documentamagjoa00palagoog (Google scan of the Oxford copy;
printed page n = leaf n+20, page/nN_w1800). The OCR was used to find the
places; every excerpt was read against the page images. Palacký's text is kept
as printed, with his spelling (Hus, Chlum, Palecz), his dates in brackets and
his quotation marks; his notes of the manuscripts are not carried. Cuts are
marked [...].
English: the site's working translation (CC0).

Each unit: pg (Palacký page), titel, orig, en, note."""

JOURNEY = [
 {"pg": "237–238",
  "titel": "The safe conduct",
  "orig": "Anno domini MoCCCCXIIIIo serenissimus princeps et dominus, D. Sigismundus Romanorum et Hungariae rex &c. postquam una cum papa Joanne XXIII indixisset et publicari mandasset generale concilium in Constantia in partibus Sueviae celebrandum, misit de Lombardia certos nobiles dominos de Bohemia, consiliarios et familiares suos, injungens eisdem, ut M. Joannem de Husinecz, sacrae theologiae batcalaureum formatum, regio ipsius nomine inducere velint et assecurare ipsius salvo conductu et nomine, ut ipse tum pro exstirpanda sua, tum etiam regni Bohemiae sinistra infamia, velit venire Constantiam ad dictum concilium generale, quia etiam vellet illi suos speciales salvos conductus dirigere, libere ut Constantiam veniens, e converso redire ad Bohemiam possit, et ipsum spondens etiam in suam et sacri imperii protectionem recipere pariter et tutelam; unde postea illi eosdem salvos conductus direxit obviam duplicatos, tam latine quam teutonice scriptos, quorum tenor in latino sequitur in haec verba: Sigismundus dei gratia Romanorum rex semper Augustus et Hungariae, Dalmatiae, Croatiae &c. rex, universis et singulis principibus, ecclesiasticis et secularibus, [...] ceterisque nostris et imperii sacri subditis et fidelibus, ad quos praesentes pervenerint, gratiam regiam et omne bonum. Venerabiles, illustres, nobiles et fideles dilecti! Honorabilem magistrum Joannem Hus, sacrae theologiae baccalaureum formatum et artium magistrum, praesentium ostensorem, de regno Bohemiae ad concilium generale in civitate Constantiensi celebrandum in proximo transeuntem, quem etiam in nostram et sacri imperii protectionem recepimus et tutelam, vobis omnibus et vestrum cuilibet pleno recommendamus affectu, desiderantes, quatenus ipsum, dum ad vos pervenerit, grate suscipere, favorabiliter tractare, ac in his, quae celeritatem et securitatem ipsius concernunt itineris, tam per terram quam per aquam, promotivam sibi velitis et debeatis ostendere voluntatem, nec non ipsum cum famulis, equis, valisiis, arnesiis et aliis rebus suis singulis per quoscumque passus, portus, pontes, terras, dominia, districtus, jurisdictiones, civitates, oppida, castra, villas et quaelibet loca alia vestra sine aliquali solutione dacii, pedagii, tributi et alio quovis solutionis onere omnique prorsus impedimento remoto transire, stare, morari et redire libere permittatis, sibique et suis, dum opus fuerit, de securo et salvo velitis et debeatis providere conductu, ad honorem et reverentiam nostrae regiae majestatis. Datum Spirae anno domini MoCCCCoXIIIIo, XVIIIo die Octobris, regnorum nostrorum anno Hungariae &c. XXXIII, Romanorum vero quinto. Ad mandatum domini regis: Michael de Prziest, canonicus Vratislaviensis.",
  "en": "In the year of the Lord 1414 the most serene prince and lord, the lord Sigismund, king of the Romans and of Hungary etc., having summoned together with Pope John XXIII a general council to be held at Constance in the region of Swabia and ordered it to be published, sent from Lombardy certain noble lords of Bohemia, his counsellors and household, charging them to persuade Master John of Husinec, formed bachelor of sacred theology, in the king's own name, and to assure him of his safe conduct and name, that he should come to Constance to the said general council, to clear away the evil name both of himself and of the kingdom of Bohemia; for he would also send him his own special letters of safe conduct, so that he might come freely to Constance and, in turn, return to Bohemia; and he pledged himself also to take him into his protection and that of the holy empire. And afterwards he sent him those letters of safe conduct to meet him, in two copies, written in Latin and in German, of which the Latin reads as follows: Sigismund, by the grace of God king of the Romans, ever augustus, and king of Hungary, Dalmatia, Croatia etc., to all and each of the princes, ecclesiastical and secular, [...] and to our other subjects and those of the holy empire, to whom these presents come, royal grace and every good. Venerable, illustrious, noble and faithful beloved! The honourable Master John Hus, formed bachelor of sacred theology and master of arts, bearer of these presents, who is about to travel from the kingdom of Bohemia to the general council to be held in the city of Constance, and whom we have taken into our protection and that of the holy empire, we commend to you all and to each of you with full affection, desiring that when he comes to you, you receive him kindly, treat him favourably, and show him a helpful will in whatever concerns the speed and safety of his journey, by land as by water; and that you let him, with his servants, horses, bags, harness and all his other things, pass, stay, remain and return freely through any passes, ports, bridges, lands, lordships, districts, jurisdictions, cities, towns, castles, villages and any other places of yours, without any payment of duty, toll, tribute or any other charge, and with every hindrance removed; and that, when there is need, you provide him and his men with a secure and safe conduct, for the honour and reverence of our royal majesty. Given at Speyer in the year of the Lord 1414, on the eighteenth day of October, in the thirty-third year of our reign in Hungary etc., and the fifth as king of the Romans. By order of the lord king: Michael of Přestanov, canon of Breslau.",
  "note": "The document that gives the companion game its title. It promises passage 'to stay, remain and return freely'; it does not promise a verdict, and nothing in it binds the council. Hus had left Prague on 11 October, before the letter was issued; it reached him on the road, and he arrived at Constance on 3 November. Sigismund was king of Hungary and king of the Romans, not yet emperor, and heir to his brother Wenceslas IV of Bohemia. 'Michael de Prziest' is the notary of the royal chancery who signed it."},
]

ARREST = [
 {"pg": "247–248",
  "titel": "A rumour and a haycart",
  "orig": "Cum autem dictus M. Joan. Hus Constantiae staret ad tres hebdomadas cum media, famabatur per civitatem, quod M. Hus ductus fuisset extra civitatem in curru, in quo foenum vehebatur vel ducebatur, sed falsum fuit. Sic enim fuit: famuli equitantes cum dicto curru pro foeno, pannum vel tegumentum, vulgariter sperloch, de curru non deposuerunt, sed post binam vel trinam ductionem primo deposuerunt et sine tecto illo iterum foenum duxerunt. Ex illo tunc aliqui opinabantur vel famabatur, quod M. Hus jam esset extra civitatem in foeno eductus, et sic quod evasisset in foeno et extra ductus fuisset; sed in rei veritate nec mentio aliqua de illa re fuit aliquando, sicut postea patuit et jam patet. Qui si evasisset, numquam comprehensus fuisset et vinculis mancipatus, et nec finaliter ab eis condemnatus.",
  "en": "When the said Master John Hus had been at Constance three and a half weeks, it was rumoured through the city that Master Hus had been taken out of the city in a cart used for carrying hay; but it was false. This is how it was: the servants who rode out with the cart for hay did not take the cloth or cover, called in the vernacular a sperloch, off the cart, but only after two or three trips took it off and carried hay again without that cover. From this some then supposed, or it was rumoured, that Master Hus had already been taken out of the city in the hay, and so had escaped in the hay and been carried out; but in truth there was never any mention of such a thing, as afterwards appeared and now appears. Had he escaped, he would never have been seized and put in chains, nor in the end condemned by them.",
  "note": "The story of the haycart was later told as fact: that Hus had tried to flee and so forfeited his safe conduct. Peter of Mladoňovice, a bachelor of Prague and secretary to Hus's protector Jan of Chlum, was at Constance throughout; his account is the eyewitness report of Hus's party, written soon after 1415."},
 {"pg": "248",
  "titel": "'Even the devil should be heard'",
  "orig": "Ex tunc quarta feria, scilicet post Katherinae (28 Nov.), cardinales, qui tunc erant Constantiae, per dictos ejus aemulos, scilicet Palecz et Michaelem de Causis instigati, miserunt duos episcopos, scilicet Augustensem et Tridentinum, magistrum civium civitatis Constantiensis et militem quendam Hans von Poden, ad hospitium ipsius M. Hus; qui cum hora prandii venissent, dixerunt ad D. Joannem de Chlum, qualiter venissent ex parte cardinalium et de mandato papae ad M. Joan. Hus, et sicut ipse prius optabat loqui illis, quia jam essent parati ipsum audire. Et D. Joannes de Chlum primum surgens, valde iracunde loquebatur ad eosdem, dicens: Scitisne patres reverendissimi, quomodo et per quem modum huc venit M. Joan. Hus? Si autem ignoratis, ecce, ego dicam vobis, quia cum nos, scilicet ego et D. Wenceslaus de Lestna fuimus in Friolia cum domino nostro imperatore, et habebamus propositum redeundi ad regnum nostrum sive provinciam, ipse tunc mandavit nobis, ut nos M. Joannem assecuraremus suo salvo conductu et sic ut veniret ad praesens concilium: propter quod scitote, quod vos contra honorem domini nostri non faciatis. Et ad magistrum civium dixit in Teutonico: Vos sciatis, quia si diabolus veniret ad videndum causam suam, ipse deberet veraciter audiri.",
  "en": "Then on the Wednesday after St Catherine's (28 November), the cardinals who were then at Constance, stirred up by his said rivals, namely Páleč and Michael de Causis, sent two bishops, namely of Augsburg and of Trent, the burgomaster of the city of Constance and a certain knight, Hans von Poden, to Master Hus's lodging. They came at the hour of the midday meal and told the lord Jan of Chlum that they had come on behalf of the cardinals and by order of the pope to Master John Hus, since he had earlier wished to speak with them, and they were now ready to hear him. And the lord Jan of Chlum rose first and spoke to them very angrily, saying: Do you know, most reverend fathers, how and in what way Master John Hus came here? If you do not know, look, I will tell you: when we, that is I and the lord Wenceslas of Leštno, were in Friuli with our lord the emperor, and meant to return to our kingdom or province, he then commanded us to assure Master John of his safe conduct, so that he would come to the present council. Know therefore that you are not to act against our lord's honour. And to the burgomaster he said in German: You should know that if the devil came to see to his own case, he ought truly to be heard.",
  "note": "Stephen Páleč, once Hus's friend at Prague, and Michael de Causis, a Prague priest who had fled to the curia, were his accusers at Constance. Jan of Chlum and Wenceslas of Dubá and Leštno were the noblemen Sigismund charged with bringing Hus; Peter of Mladoňovice was Chlum's secretary. Chlum calls Sigismund 'emperor', which he was not yet."},
 {"pg": "248–249",
  "titel": "'I came to the whole council'",
  "orig": "Et M. Joannes Hus, surgens a mensa, quem ut puto nullus episcoporum adhuc noverat, respondit: „Ego non veni ad cardinales huc tantum, nec umquam optabam loqui illis seorsum, sed ad totum concilium veni, et ibi loquar, quidquid deus dederit et de quibus interrogatus fuero; sed tamen ad petitionem dominorum cardinalium ego paratus sum adstatim venire ad ipsos, et si interrogabor de aliquo, spero, quia potius volo mortem eligere, antequam veritatem ex scripturis vel alias mihi cognitam denegarem.“ Et dicti episcopi, et alii ad ipsum M. Joann. Hus venientes, sub illa collocutione amicabili, qua ipsum M. Hus finaliter petebant, ut veniat ad dictos cardinales, quia ipsi vellent loqui sibi, munierant domum habitationis M. Hus et aliquot alias circum circa vicinas armatis de dicta civitate. Et magistro descendente, obviam dedit sibi hospita, quam valedixit, dicens: „Benedicat te deus,“ quae respondens flevit.",
  "en": "And Master John Hus, rising from the table (none of the bishops, I think, knew him yet), answered: 'I did not come here to the cardinals only, nor did I ever wish to speak with them apart; I came to the whole council, and there I will speak whatever God gives me and whatever I am asked about. Yet at the request of the lord cardinals I am ready to come to them at once; and if I am questioned about anything, I hope that I would rather choose death than deny the truth I know from the scriptures or otherwise.' And while the said bishops and the others who had come to Master John Hus held this friendly conversation, in which they finally asked Master Hus to come to the said cardinals because they wished to speak with him, they had surrounded the house where Master Hus lodged, and several neighbouring houses round about, with armed men of the city. And as the master came down, his hostess met him, and he took leave of her, saying 'God bless you'; and she wept as she answered.",
  "note": "The distinction he draws, between the cardinals and 'the whole council', was the one on which he had come: to be heard publicly, not examined privately."},
 {"pg": "249",
  "titel": "'Good words'",
  "orig": "Et cum venisset ad cardinales et ipsos salutasset, dixerunt ad eum: Magister Joannes! multa et mirabilia dicuntur de vobis, quod vos multos errores tenueritis et seminaveritis in regno Bohemiae; et ideo vos vocare fecimus, volentes loqui vobis, si ita est. Et ipse respondit: Reverendissimi patres! sciat Vestra Paternitas, quod antequam unum errorem tenere vellem, potius vellem mori. Et ecce, libere veni ad istud sacrum concilium, et docto, quod alicubi erravi, paratus sum humiliter corrigi et emendare. Et cardinales dixerunt: Et pro certo ista sunt bona verba. Et his dictis abierunt ad propria, magistro ibidem sub custodia armatorum relicto. Et D. Joannes mansit secum.",
  "en": "And when he had come to the cardinals and greeted them, they said to him: Master John! Many strange things are said of you, that you have held and sown many errors in the kingdom of Bohemia; and so we had you called, wishing to speak with you, whether it is so. And he answered: Most reverend fathers! Let your paternity know that rather than hold a single error I would die. And see, I have come freely to this holy council, and if I am shown that I have erred anywhere, I am ready to be humbly corrected and to amend. And the cardinals said: Those are certainly good words. And having said this they went off to their own lodgings, leaving the master there under armed guard. And the lord Jan stayed with him.",
  "note": "28 November 1414. From this day Hus was a prisoner, first in the house of a canon, then from 6 December in the Dominican convent on the island in the Rhine, later in the castle of Gottlieben. Sigismund, who reached Constance at Christmas, protested and then let the council keep him. The formula Hus uses, ready to be corrected 'if shown' his error from scripture, is the one he held to the end (Mlad. Sentence [1])."},
]

HEARINGS = [
 {"pg": "284",
  "titel": "The king speaks of the safe conduct",
  "orig": "Et rex dixit: Audias Joannes Hus! Dixerunt aliqui, quod primo post XV dies captivitatis tuae tibi salvum conductum dedissem: ego dico, quod non est verum, quia ego volo probare cum principibus et aliis quam pluribus, quod ego dedi tibi salvum conductum etiam prius quam de Praga exivisti, et etiam mandavi ibidem dominis Wenceslao et Joanni, ut te adducerent et assecurarent, ut libere te venientem ad Constantiam non opprimerent, sed ut tibi publicam darent audientiam, ut possis de fide tua respondere. Quod et fecerunt, et hic tibi publicam audientiam et pacificam et honestam dederunt, et ego regratior ipsis, licet dicant alii, quod ego non possem dare salvum conductum haeretico, vel de haeresi suspecto. Et ideo sicut hic D. Cardinalis consulit tibi, ita et ego consulo tibi, quod tu nihil teneas pertinaciter, sed in istis, quae hic sunt contra te probata et quae confessus es, des te totaliter ad gratiam sacri concilii, et ipsi tibi propter nos et honorem nostrum et fratrem nostrum et regnum Bohemiae facient gratiam aliqualem, et poenitentiam suscipias pro eisdem. Si vero vis pertinaciter illos tenere, vere tunc ipsi bene sciunt, quid debeant tecum facere. Ego dixi eis, quia nullum volo haereticum defendere, imo si unus vellet in sua haeresi esse pertinax, ego solus vellem succendere et comburere ipsum; sed ego consulerem tibi, quod tu totaliter te dares ad gratiam concilio, et quanto citius, tanto melius, ne in profundiores involvaris errores. Et ipse respondit ad primum: Ego regratior Serenitati Vestrae de salvo conductu, quod Serenitas Vestra mihi eundem dare dignata est gratiose.",
  "en": "And the king said: Hear, John Hus! Some have said that I gave you the safe conduct only fifteen days after your arrest. I say that it is not true, for I will prove with the princes and very many others that I gave you the safe conduct even before you left Prague, and also ordered the lords Wenceslas and Jan there to bring you and assure you, so that when you came freely to Constance they should not oppress you, but give you a public hearing, so that you could answer for your faith. And they have done so, and have given you here a public, peaceful and honourable hearing, and I thank them for it, although others say that I could not give a safe conduct to a heretic or to one suspected of heresy. And therefore, as the lord cardinal here advises you, so I too advise you to hold nothing pertinaciously, but in the things that have been proved against you here and that you have confessed, to give yourself wholly to the grace of the holy council; and for our sake and our honour, and for our brother's and the kingdom of Bohemia's, they will show you some grace, and you will do penance for them. But if you mean to hold them pertinaciously, then truly they know well what they must do with you. I have told them that I will defend no heretic; indeed, if anyone meant to be pertinacious in his heresy, I would light the fire and burn him myself. But I would advise you to give yourself wholly to the grace of the council, and the sooner the better, lest you be entangled in deeper errors. And he answered to the first: I thank your serenity for the safe conduct, which your serenity deigned so graciously to give me.",
  "note": "7 June 1415, the second public hearing, in the refectory of the Franciscan convent, after an eclipse of the sun in the morning. The king's defence is the whole argument about the safe conduct in his own words: it was given in time, and it was kept, because it promised a hearing. 'The lord cardinal' is Pierre d'Ailly, cardinal of Cambrai, who had just advised Hus to submit."},
 {"pg": "314–315",
  "titel": "'Do not believe him if he recants'",
  "orig": "Post hoc episcopus Rigensis magistrum Hus recepit, ut iret ad locum carceris; quem transeuntem dominus Joannes de Chlum salutans et manum illi exhibens consolabatur, qui valde gratus fuit de illo, quod ipsum jam quasi ab omnibus rejectum, spretum et haereticatum non erubuit nec est veritus salutare et illi publice manum porrigere; et hoc idem postea domino Joanni intimavit. Et post recessum ejus omnes, qui ibi erant in eodem loco, praelati et cardinales volebant recedere, et jam surrexerant. Tunc armati, qui retro custodiebant, etiam recesserunt, et nostri appropinquaverunt ad fenestram, et dominus Joannes de Chlum et dominus Wenceslaus de Lestna et P. baccalaureus interius adhuc erant, quos, ut videtur, rex non consideravit, sed aestimabat eos recessuros tunc, quando magister ducebatur ad carceres. Dixitque rex: Patres reverendi! jam audistis, quod etiam ex multis illis, quae sunt in libris ejus, et quae confessus est, et quae contra eum sufficienter probata sunt, sufficeret sibi pro condemnatione unum illorum. Et ergo si noluerit illos errores revocare et abjurare et contra illos determinare, tunc comburatur vel vos cum ipso secundum jura vestra faciatis sicut scitis. Et sciatis, quod quaecumque promitteret vobis, quod vellet revocare, vel quod hic revocaret, non credatis ei, nec ego sibi crederem, quia veniens ad regnum et suos fautores illos et plures alios errores seminaret, et fieret novissimus error pejor priore. Et ideo inhibeatis sibi omnino praedicationem, ne amplius praedicet, et etiam, quod non veniat amplius ad fautores suos [...]. Et ideo etiam faciatis finem cum aliis ejus occultis discipulis et fautoribus, quia ego in brevi sum recessurus, et specialiter cum isto, isto, resumendo illam dictionem „isto,“ qui hic detinetur. Et illi dixerunt: Hieronymo. Et ipse: Ita, Hieronymo.",
  "en": "After this the bishop of Riga took Master Hus to go to the place of his prison; and as he passed, the lord Jan of Chlum greeted him and, holding out his hand, comforted him; and he was very grateful for it, that when he was already rejected by almost everyone, despised and branded a heretic, Chlum was not ashamed or afraid to greet him and give him his hand in public; and he told the lord Jan the same afterwards. And after he had gone, all who were there in that place, prelates and cardinals, wished to leave, and had already risen. Then the armed men who kept guard behind also withdrew, and our people went up to a window; and the lord Jan of Chlum, the lord Wenceslas of Leštno and P., the bachelor, were still inside, whom, it seems, the king did not notice, but supposed they would leave when the master was led away to prison. And the king said: Reverend fathers! You have heard that of the many things in his books, and those he has confessed, and those sufficiently proved against him, any one would suffice for his condemnation. Therefore if he will not revoke and abjure those errors and teach against them, let him be burned, or do with him according to your laws as you know how. And know that whatever he may promise you, that he would recant, or even if he recanted here, do not believe him; nor would I believe him, for when he came to the kingdom and to his supporters he would sow those and more errors, and the last error would be worse than the first. And so forbid him to preach at all, and also that he go any more to his supporters [...]. And so make an end also of his other secret disciples and supporters, for I shall soon be leaving; and especially of that one, that one, repeating the word 'that one', who is held here. And they said: Jerome. And he: Yes, Jerome.",
  "note": "8 June 1415, after the last hearing. 'P. the bachelor' is the author himself, Peter of Mladoňovice: he heard this because the king did not see him. It is the sentence the game turns on when Hus recants: the king advised the council not to believe a recantation. Jerome of Prague, Hus's friend, arrested in April 1415, recanted in September, withdrew his recantation, and was burned on 30 May 1416."},
]

DEATH = [
 {"pg": "319–320",
  "titel": "'I came here freely'",
  "orig": "Insuper huc etiam ad hoc concilium veni libere, habens salvum conductum domini regis hic praesentis, volens meam innocentiam ostendere et de fide mea reddere rationem. Cum ergo omnes articuli contra eum oblati jam finiti fuissent et lecti, quidam auditor calvus et antiquus, et praelatus nationis Italicae deputatus legit sententiam diffinitivam contra M. Joannem Hus. Et ipse Mr Joannes ad certa puncta ejusdem sententiae, contra eandem replicans, quamvis prohibebatur, respondebat. Et specialiter cum pronuntiaretur pertinax in suo errore et haeresi, alta voce respondit: Numquam fui, sed nec sum pertinax, sed semper desideravi et die hodierna desidero informationem efficaciorem ex scripturis. Et hodie dico, quod et si uno verbo omnes errores destruere et convincere possem, libentissime hoc efficerem. Et cum omnes libri sui, sive in latino per ipsum editi, sive in aliud quodcumque idioma translati, in eadem sententia tamquam suspecti de haeresi damnarentur et damnandi ad comburendum diffinirentur, quorum certi ibidem post sunt combusti, et praesertim libellus de Ecclesia et contra Palecz, ut dicebatur, et Stanislaum: ipse M. Hus respondit: Et qualiter condemnatis mihi libros meos, cum semper desideravi et postulavi scripturas meliores contra dicta et posita in eisdem, et hodie desidero, et nec hucusque aliquam scripturam efficaciorem de opposito adduxistis, et nec ex eisdem unum verbum ostendistis erroneum; libros vero in vulgare Bohemicum vel aliud idioma translatos qualiter condemnastis, quos numquam vidistis?",
  "en": "'Moreover, I came here to this council freely, having the safe conduct of the lord king here present, wishing to show my innocence and to give an account of my faith.' When all the articles brought against him had been finished and read, a certain auditor, bald and old, a prelate deputed by the Italian nation, read the definitive sentence against Master John Hus. And Master John answered certain points of that sentence, replying against it although he was forbidden. And especially when he was pronounced pertinacious in his error and heresy, he answered in a loud voice: I never was, nor am I, pertinacious, but I have always wished, and today wish, to be better instructed from the scriptures. And today I say that if with one word I could destroy and refute all errors, I would most gladly do it. And when all his books, whether published by him in Latin or translated into any other language, were condemned in the same sentence as suspect of heresy and declared to be burned, some of which were afterwards burned there, and especially the little book On the Church and those against Páleč, as it was said, and against Stanislav: Master Hus answered: And how do you condemn my books, when I have always wished and asked for better scriptures against what is said and set down in them, and wish it today, and you have not yet brought any stronger scripture to the contrary, nor shown a single word in them to be erroneous? And how have you condemned the books translated into the Bohemian vernacular or another language, which you have never seen?",
  "note": "6 July 1415, in the cathedral of Constance, before the council in session and the king. The first sentence is Hus's own answer to the article that he had borne his excommunication contumaciously: he had appealed, sent proctors to the curia, and come to Constance under the safe conduct. The council condemned his Czech writings unread; the book On the Church is De ecclesia (1413)."},
 {"pg": "320–321",
  "titel": "The degradation",
  "orig": "Qua sententia finita, sic ut praemittitur, in singulis suis punctis, ipse M. Joannes Hus pro omnibus inimicis suis flexis iterum genibus alta voce orabat et dixit: Domine Jesu Christe! ignosce omnibus inimicis meis, propter magnam misericordiam tuam te deprecor; et tu scis, quia false accusaverunt me, falsos testes produxerunt et falsos articulos contra me confinxerunt. Ignosce eis propter immensam misericordiam tuam! [...] Cum ergo sic jam indutus esset et ab episcopis illis hortaretur, ut revocet et abjuret, surgens et supra mensam illam, antequam induebatur, ascendens, dolorose conversus ad multitudinem et flens dixit: Ecce isti episcopi hortantur me ad hoc, quod revocem et abjurem; timeo hoc facere, ne sim mendax in conspectu domini, et etiam ne conscientiam et dei veritatem offendam, cum numquam istos tenui articulos, qui contra me false testantur, sed potius his oppositum docui, scripsi et praedicavi, et etiam ideo ne tantam multitudinem, cui praedicavi, scandalisem, et etiam alios fideliter verbum dei praedicantes. Et cum haec dixisset, circumsedentes pontifices et alii de dicto concilio dixerunt: Jam videmus, quomodo induratus est in malitia sua et pertinax in haeresi! Eo vero de mensa dicta descendente, statim dicti episcopi eum degradare incipientes, calicem imprimis ab ipso auferentes et de manibus ipsius, dixerunt hanc orationem maledictionis: O Juda maledicte! ut qui dereliquisti consilium pacis et cum Judaeis consiliatus es; auferimus a te calicem hunc redemtionis. Et ipse alta voce dixit: Confido in dominum deum omnipotentem, pro cujus nomine hanc blasphemiam patienter sustineo, quod ipse suae redemtionis a me calicem non auferet, sed spero firmiter, quod hodie in regno suo bibam illum.",
  "en": "When the sentence was finished, as set out above, in each of its points, Master John Hus knelt again and prayed aloud for all his enemies, and said: Lord Jesus Christ! Forgive all my enemies, I beseech you for your great mercy; and you know that they have accused me falsely, brought false witnesses and made up false articles against me. Forgive them for your boundless mercy! [...] When he had thus been vested, and was urged by those bishops to revoke and abjure, he rose and stepped up on the table before which he had been vested, and turning sorrowfully to the crowd, weeping, said: See, these bishops urge me to revoke and abjure. I fear to do it, lest I be a liar in the sight of the Lord, and lest I offend my conscience and God's truth, for I never held these articles that are falsely witnessed against me, but taught, wrote and preached the opposite; and also lest I scandalize the great multitude to whom I have preached, and others who faithfully preach the word of God. And when he had said this, the prelates sitting round and others of the council said: Now we see how hardened he is in his malice and pertinacious in heresy! As he came down from the table, the bishops at once began to degrade him, first taking the chalice from his hands, and said this prayer of malediction: O cursed Judas, who have forsaken the counsel of peace and taken counsel with the Jews, we take from you this chalice of redemption. And he said in a loud voice: I trust in the Lord God almighty, for whose name I patiently bear this blasphemy, that he will not take from me the chalice of his redemption, and I firmly hope that today I shall drink it in his kingdom.",
  "note": "Seven bishops vested Hus as for mass and then stripped him, piece by piece, of the priesthood. His reason for refusing to recant is exact: he was asked to abjure articles he said he had never held, and to abjure them would be to confess that he had. The chalice taken from him became the sign of his followers: within months Prague was giving the cup to the laity."},
 {"pg": "321",
  "titel": "'Hic est haeresiarcha'",
  "orig": "Antequam autem coronam blasphemiae papyream suo imponerent capiti, inter cetera dixerunt ei: Committimus animam tuam diabolo. Et ipse manibus complosis et erectis in coelum oculis dixit: Et ego eam committo piissimo domino Jesu Christo. Et visa illa corona dixit: Dominus meus Jesus Christus propter me miserum multo duriorem et graviorem spineam coronam innocens ad turpissimam mortem ferre dignatus est; et ideo ego miser et peccator hanc multo leviorem, licet blasphemam, volo ferre humiliter pro ipsius nomine et veritate. Erat autem corona papyrea rotunda, ad quantitatem fere unius cubiti in altitudine, in qua tres horrendi diaboli depicti fuerunt, (quemadmodum animam vellent cum ungulis inter se trahere et tenere); et titulus in eadem corona causae ipsius inscriptus erat: Hic est haeresiarcha. Tunc rex dixit duci Lodwico, filio quondam Clem de Bavaria, qui tunc stans in suo apparatu ante ipsum pomum aureum cum cruce tenebat in manibus: Vade, accipe eum. Et Clem filius jam dictus magistrum accipiens, dedit in manus lictorum et conduxit ad mortem.",
  "en": "Before they put the paper crown of blasphemy on his head, they said to him among other things: We commit your soul to the devil. And he, with hands joined and eyes raised to heaven, said: And I commit it to the most merciful Lord Jesus Christ. And seeing that crown he said: My Lord Jesus Christ, innocent, deigned to bear for my wretched sake a much harder and heavier crown of thorns to a most shameful death; and so I, wretched and a sinner, will humbly bear this much lighter one, though blasphemous, for his name and truth. The paper crown was round, almost a cubit high, and on it three horrible devils were painted, as if they wanted to tear the soul between them with their claws and hold it; and the title of his cause was written on the crown: Hic est haeresiarcha, 'this is a heresiarch'. Then the king said to Duke Ludwig, son of the late Clem of Bavaria, who was standing in his robes before him holding the golden orb with the cross: Go, take him. And Clem's son took the master, gave him into the hands of the executioners, and led him to his death.",
  "note": "Ludwig III, Elector Palatine, son of the late King Rupert ('Clem'), was the imperial officer who received the condemned from the Church. The council did not burn; it 'relinquished' the heretic to the secular arm, and the king of the Romans gave the order in two words."},
 {"pg": "322–323",
  "titel": "'Today I will gladly die'",
  "orig": "Locus vero tormentorum fuit inter hortos in prato certo, exeundo de civitate Constantia versus propugnaculum Gotlebense inter portas et fossata praeurbii dictae civitatis. [...] Exutus vero veste sua, ad statuam quandam alligatus est funibus a tergo versis manibus dictae statuae alligatus. Et cum facie ad orientem versus fuisset, dixerunt quidam astantium: Non vertatur versus orientem, quia haereticus est, sed versus occidentem ipsum divertite; quod et factum est. [...] Antequam vero succenderetur, venit ad eum marsalcus imperii Happe de Poppenhem et cum eo filius quondam Clem, ut dicebatur, ipsum adhortantes, ut adhuc vitam conservet incolumem, et ut praedicata olim per se et dicta sua abjuret et revocet. Qui in coelum respiciens, alta voce respondit: Deus mihi, inquit, testis est, quod ea, quae false mihi ascribuntur, per falsos testes mihi imposita, numquam docui nec praedicavi, sed de principali intentione meae praedicationis et omnium aliorum meorum actuum vel scriptorum exstitit, ut solum homines retrahere possem a peccatis; in ea vero evangelii veritate, quam scripsi, docui et praedicavi ex dictis et ex positionibus sanctorum doctorum hodie laetanter volo mori. Et hoc audito, statim dictus marsalcus una cum filio Clem concutientes manus abscesserunt. Quem mox lictores succenderunt, et magister mox alta voce cantavit primo: „Christe fili dei vivi miserere nobis;“ secundo: „Christe fili dei vivi miserere mei“; tertio vero cum cantare coepisset: „Qui natus es ex Maria virgine:“ mox ventus flammam sibi commovit in faciem, et sic in se ipso orans, labiis movens et capite, exspiravit in domino.",
  "en": "The place of execution was among the gardens in a certain meadow, going out of the city of Constance towards the fort of Gottlieben, between the gates and the moats of the city's suburb. [...] Stripped of his clothes, he was bound to a stake with ropes, his hands tied behind him to the stake. And when he was facing east, some of the bystanders said: Let him not be turned to the east, for he is a heretic; turn him to the west; and it was done. [...] Before it was lit, the marshal of the empire, Haupt von Pappenheim, came to him, and with him the son of the late Clem, as it was said, urging him even now to keep his life safe, and to abjure and revoke what he had once preached and said. And he, looking to heaven, answered in a loud voice: God is my witness, he said, that the things falsely ascribed to me and laid on me by false witnesses I never taught nor preached; the chief intention of my preaching and of all my other acts and writings was only that I might turn men from sin. In that truth of the gospel which I have written, taught and preached from the sayings and expositions of the holy doctors, today I will gladly die. And when they heard this, the marshal and Clem's son at once struck their hands together and went away. Then the executioners lit the fire, and the master at once sang in a loud voice, first: 'Christ, son of the living God, have mercy on us'; second: 'Christ, son of the living God, have mercy on me'; and third, when he had begun to sing 'who was born of the virgin Mary', the wind blew the flame into his face; and so, praying within himself and moving his lips and head, he died in the Lord.",
  "note": "The last offer of recantation came at the stake, from the emperor's marshal. Hus's answer repeats, word for word in substance, what he had said at the arrest and in the cathedral: he would not abjure what he had never held, and would die in what he had taught."},
 {"pg": "323",
  "titel": "Into the Rhine",
  "orig": "Cum vero ligna dictorum fasciculorum et funium exusta fuissent, et adhuc gleba corporis staret in dicta catena pendens per collum, mox lictores dictam glebam una cum statua truserunt in terram, et ignibus amplius et tertia biga de lignis auctis exurebant et circumeuntes fustibus ossa concutiebant, ut eo citius incinerarentur. [...] Et tunicam ex mandato dictorum Clem et marsalconis lictores jecerunt unacum sotularibus in ignem, dicentes, ne Bohemi illud pro reliquiis habeant, et nos dabimus tibi pretium tuum pro illo; qui et fecerunt. Et sic unacum singulis dictis titionum cineribus cuidam carrucae imponentes, ad Rheni flumen vicinum ibidem dimersum projecerunt.",
  "en": "When the wood of the said bundles and the ropes had burned away, and the lump of the body still stood hanging by the neck in the said chain, the executioners at once pushed the lump down to the ground together with the stake, and burned it further with fire fed by a third cartload of wood, and going round it broke the bones with clubs, so that they would turn to ashes the sooner. [...] And by order of Clem's son and the marshal the executioners threw his coat into the fire, together with his shoes, saying: 'lest the Bohemians have it as a relic; and we will give you its price'; and so they did. And so, putting all the ashes together with the brands on a cart, they threw them into the Rhine, which flows near by.",
  "note": "The burning of the coat and shoes 'lest the Bohemians have it as a relic' shows that the authorities already expected what followed: in Bohemia Hus was venerated as a martyr, and 6 July became a feast day of the Utraquist church."},
]

SECTIONS = [
    {"id": "journey", "zk": "Mlad. Journey", "titel": "The safe conduct",
     "blurb": "Sigismund's promise and his letter of 18 October 1414, as the eyewitness copied it: free passage to Constance, to stay, and to return.",
     "units": JOURNEY},
    {"id": "arrest", "zk": "Mlad. Arrest", "titel": "The arrest (28 November 1414)",
     "blurb": "Three and a half weeks after his arrival, a false rumour of flight in a haycart; two bishops at the lunch table; Jan of Chlum's anger ('even the devil should be heard'); and a hearing that turns into a prison.",
     "units": ARREST},
    {"id": "hearings", "zk": "Mlad. Hearings", "titel": "The hearings (7 and 8 June 1415)",
     "blurb": "Sigismund defends his safe conduct to Hus's face and advises him to submit; after the last hearing, not seeing Hus's friends at the window, he tells the council not to believe a recantation, and to make an end of Jerome too.",
     "units": HEARINGS},
    {"id": "sentence", "zk": "Mlad. Sentence", "titel": "The sentence and the fire (6 July 1415)",
     "blurb": "In the cathedral: the sentence, the books condemned unread, the degradation and the paper crown; outside the walls: the last offer to recant, the stake, the Kyrie, and the ashes thrown into the Rhine.",
     "units": DEATH},
]
